src/components/Torrent.vue
src/models/torrent.js

Since most of my already existing torrents were showing up as failed I fixed that. Also I fixed the fact that you could select the text inside the torrents, which was annoying me

Added more torrent statuses and removed the ability to select the text in the torrents themselves

---

src/components/Modals/SettingsModal/Tabs/BitTorrent.vue

This fixes the typo in BitTorrent Modal in VueTorrent settings.

Fixes typo in VueTorrent settings modal.

---

README.md
src/assets/styles.scss
src/components/Modals/AddModal.vue
src/models/torrent.js
src/styles/variables.scss

- add file input rule fallback
- Fixes #66 
- [what it looks like now](https://github.com/jef/VueTorrent/blob/jef/regex-torrent-check/README.md)
- clean up
- add git information
- change `moving` state to its own separate style
- Fixes #67

feat: torrent check fallback, README cleanup, torrent states

---

src/components/Modals/SettingsModal/Tabs/Vuetorrent/General.vue

- Add links to VueTorrent and qBittorrent releases
Not sure if I did this right (feel free to fix). Let me know what you think.
Thanks!

feat: add links to versions

---

README.md

- add NGINX config
- N/A
- formatting
- update language

Add NGINX config

---

src/models/Torrent.js

- Torrent detail modal multiple tags highlight

fix: torrent detail modal multiple tags highlight

---

src/components/Modals/SettingsModal/Tabs/Vuetorrent/General.vue

Updates link to proper release

chore: update link on new tags

---

src/components/Modals/TorrentDetailModal/Tabs/Trackers.vue

Does not close after clicking close. There is a problem with the declaration.
- AddTrackers dialog bug fix

AddTrackers dialog bug fix

---

src/components/Modals/TorrentDetailModal/Tabs/Peers.vue

auto refresh peers
- automatic refresh of peer list on detail page
- some layout bugs and improvements

refresh peers on detail page

---

src/actions/DocumentTitle.js

Fix for global speed title [fix]
Download and upload speed were exchanged.

Fix Global Speed Title

---

src/lang/zh.js

Add Chinese translation file at src/lang/zh.js
`npm run serve` command has an error on my PC and I cannot solve it, so there is no screenshot in this PR.

add Chinese Translation

---

src/lang/en.js
src/lang/it.js

translation: Add it.js

---

src/lang/pt-br.js

added brazilian portuguese language
Please explain what kind of feature your PR's brings or what kind of bug it fixes.
Feel free to include screenshots for UI related changes.
Keep all the commits inside your PR related to topic of the PR, otherwise create a seperate PR

feat: add Portuguese (Br)

---

src/lang/zh-hans.js
src/lang/zh-hant.js

Finish Chinese translations for two variants.

chore: Chinese translations

---

src/lang/zh-hant.js

fix: Traditional Chinese translation

---

docker-compose.yml
src/App.vue
src/services/qbit.js

No longer do an empty `POST` to `/login`.
I think this might be a cleaner way to check if the user is already authenticated.
Closes  #396

perf: better authenticated check

---

src/lang/zh-hant.js

perf: update Traditional Chinese translations

---

src/components/Modals/SpeedLimitModal.vue
src/lang/zh-hant.js

Please explain what kind of feature your PR's brings or what kind of bug it fixes.
Feel free to include screenshots for UI related changes.
Keep all the commits inside your PR related to topic of the PR, otherwise create a seperate PR

fix: speed limit dialog incorrect text display and zh-hant fix

---

src/lang/fr.js

Completed the french translation with the new missings one
- [X ] I've started from master
- [X ] I've only committed changes related to this PR
- [X ] All Unit tests pass
- [X ] I've removed all commented code
- [X ] I've removed all unneeded console.log statements

perf: complete French translation

---

src/lang/en.js

fixed:
- Status selector Downloading item case
- torrents grid Upload, Downloaded, Uploaded label case
- add torrent category selector title case
- context menu set limit Upload case
- context menu copy Hash misspelling

fix: non-capital words

---

.gitignore
src/components/Modals/Rss/FeedForm.vue
src/components/Modals/Rss/RuleForm.vue
src/components/Modals/Rss/index.js
src/components/Settings/Tabs/Rss.vue
src/components/Settings/Tabs/Rss/Feeds.vue
src/components/Settings/Tabs/Rss/General.vue
src/components/Settings/Tabs/Rss/Rules.vue
src/components/Settings/Tabs/index.js
src/lang/en.js
src/services/qbit.js
src/store/getters.js
src/store/index.js
src/store/mutations.js
src/views/Settings.vue

Step 1 of adding RSS support: 
Step 2:

feat: basic rss interface (#447)

---

src/lang/zh-hans.js

Updated translations of new items introduced in v0.18.0

chore: Update Simplified Chinese translation.

---

src/lang/ua.js

Improved Ukrainian translation

---

src/lang/zh-hant.js

chore: Update Traditional Chinese translation

---

src/lang/ja.js

- Japanese translate file updated with reference to English file
- No other files have been changed
I'm using this updated file.
So this PR should complete checklist.

update ja translate file

---

src/lang/ru.js

fix type errors (7 errors) - verified , the build now is successful
Sorry inattentively checked the previous committees :)

fix type errors (7 errors) - verified , the build is successful

---

src/components/TorrentDetail/Tabs/Content.vue
src/services/qbit.js

This PR adds the ability to rename a folder within the Content tab in the Torrent Details.
It will fix issue #358

Support for renaming folders

---

tests/unit/General.spec.js
tests/unit/__snapshots__/General.spec.js.snap

I've added testcases for general component, which have increased coverage of it. Please add "**HACKTOBERFEST-ACCEPTED**" label to this PR. It will help me to complete the task. Thank you.
Keep all the commits inside your PR related to topic of the PR, otherwise create a seperate PR

chore: add testcases for General Component

---

vue.config.js

see
https://stackoverflow.com/questions/51777346/cookies-not-sent-with-request-for-web-app-manifest-json

fix: cookies not sent with request for Web App manifest.json

---

tests/unit/BitTorrent.spec.js
tests/unit/Dashboard.spec.js
tests/unit/__snapshots__/BitTorrent.spec.js.snap
tests/unit/__snapshots__/Dashboard.spec.js.snap

Added testcases testcases for Dashboard and BitTorrent Components.

chore: add testcases for Dashboard and BitTorrent Components

---

src/components/TorrentDetail/Tabs/Info.vue
src/filters.js
src/helpers.js
tests/unit/filters.spec.js
tests/unit/helpers.spec.js

I have used conditional rendering, to render clickable links in torrent details view. There was issue with previous feature, because v-html allows to achieve XSS easily. I have removed old code from filters and replaced it with helper functions.
https://github.com/WDaan/VueTorrent/pull/506

fix/feat: Conditional rendering in torrent details view

---

src/lang/id.js
src/lang/zh-hant.js

chore: update Indonesian Translation

---

src/lang/ru.js

I corrected/adapted the translation of some lines.

chore: update Russian Translation

---

src/components/Modals/TagsAndCategories/CreateCategoryDialog.vue
src/components/Modals/TagsAndCategories/CreateTagDialog.vue
src/lang/en.js
src/lang/fr.js
src/lang/id.js
src/lang/ja.js
src/lang/ru.js
src/lang/ua.js
src/lang/zh-hans.js
src/lang/zh-hant.js

Removed return statement that blocked category creation action

fix: Enabled category creation

---

src/styles/styles.scss

This PR improves visibility by adding a white color to the caret in inputs.

feat: Improve caret visibility for dark theme

---

src/components/Torrent/TorrentRightClickMenu.vue

Adds a scrollbar for long lists in the TorrentRightClickMenu component
Fixes #565

perf: Add scroll support in TorrentRightClickMenu

---

.gitignore
src/components/Settings/Tabs/Downloads.vue
src/lang/en.js
src/lang/ru.js
src/plugins/i18n.ts
src/store/getters.js

Adds plural rules for Russian and improves translation

Some i18n improvements

---

src/lang/zh-hans.js

Please explain what kind of feature your PR's brings or what kind of bug it fixes. Feel free to include screenshots for UI related changes. Keep all the commits inside your PR
related to topic of the PR, otherwise create a seperate PR

chore: Update Simplified Chinese translation

---

src/components/Modals/AddModal.vue
src/components/Torrent/TorrentRightClickMenu.vue
src/lang/en.json
src/lang/fr.json

Add toasts for clipboard actions

perf: Add toasts for copy/paste success/error

---

src/components/Modals/Rss/FeedForm.vue
src/components/Modals/Rss/RuleForm.vue
src/components/Navbar/TopActions.vue
src/components/Settings/Tabs/Rss/Feeds.vue
src/lang/en.json
src/lang/fr.json
src/mixins/General.ts
src/router.ts
src/services/qbit.ts
src/store/mutations.ts
src/types/qbit/models/Feed.ts
src/types/qbit/models/FeedArticle.ts
src/types/qbit/models/index.ts
src/types/qbit/payloads/CreateFeedPayload.ts
src/types/qbit/payloads/index.ts
src/types/vuetorrent/rss/Feed.ts
src/types/vuetorrent/rss/FeedArticle.ts
src/types/vuetorrent/rss/index.ts
src/views/RssArticles.vue
vite.config.js

Added new button to TopActions to display RSS Articles in a new view linked with the router.
I took the opportunity to add RSS feeds' name text field to the FeedForm modal and edit icon in the settings page.
#311 is fixed ?
and #609 👀

Add RSS articles view

---

src/components/Torrent/TorrentRightClickMenu.vue
src/lang/en.json
src/lang/fr.json
src/services/qbit.ts
vite.config.js

Added option to export torrents from TRC
Fixes #624

Add export torrent to TRC menu

---

src/lang/vi.json

Please explain what kind of feature your PR's brings or what kind of bug it fixes. Feel free to include screenshots for UI related changes. Keep all the commits inside your PR
related to topic of the PR, otherwise create a seperate PR

[chore] Update Vietnamese translation

---

src/views/RssArticles.vue

perf: Fill data table width to whole page

---

src/components/Modals/TagsAndCategories/CreateTagDialog.vue
src/components/Settings/Tabs/TagsAndCategories.vue
src/components/Torrent/TorrentRightClickMenu.vue
src/components/TorrentDetail/Tabs/TorrentTagsAndCategories.vue

Fix problems with qbit service interactions that prevented actions on tags and categories

fix: Unable to delete / create tags and categories

---

src/services/qbit.ts
src/views/RssArticles.vue

add mark as read behavior for rss articles with visual affect for read articles

perf: add mark as read behavior for rss articles

---

src/components/Modals/SearchModal/SearchModal.vue
src/lang/en.json
src/lang/fr.json
src/views/RssArticles.vue

This PR adds a checkbox to filter unread articles in RSS datatable

Add RSS unread filter

---

src/components/TorrentDetail/Tabs/DetailPeers.vue
src/services/qbit.ts

Fix peers not showing up in the peers data table (leftover from the TS migration, no big deal)
Fixes #652

fix: peers not showing up

---

package-lock.json
package.json
src/components/Modals/AddModal.vue
src/components/Settings/Tabs/BitTorrent.vue
src/components/Settings/Tabs/Connection.vue
src/components/Settings/Tabs/Downloads.vue
src/components/Settings/Tabs/VueTorrent/VGeneral.vue
src/enums/qbit/AppPreferences.ts
src/enums/qbit/ContentLayout.ts
src/enums/qbit/StopCondition.ts
src/enums/qbit/index.ts
src/lang/en.json
src/lang/fr.json
src/lang/id.json
src/lang/ja.json
src/lang/ru.json
src/lang/uk.json
src/lang/vi.json
src/lang/zh-hans.json
src/lang/zh-hant.json
src/mixins/SettingsTab.ts
src/types/qbit/models/AppPreferences.ts

fix: Replace root_folder param with contentLayout & stopCondition

---

src/components/Modals/AddModal.vue

Fix Drag-and-Drop not working after #665 (f0ddc603bdab2c5ee155e2289d573818407cf4d9)

fix: Drag-and-Drop not working

---

src/lang/en.json
src/lang/fr.json

Rework toast message to indicate that context isn't secured.
See #666

perf: Rework toast msg for clipboard API

---

package-lock.json
package.json
src/components/Settings/Tabs/VueTorrent/VGeneral.vue
src/lang/en.json
src/lang/fr.json
src/schemas/StoreState.json
src/schemas/index.ts
src/services/qbit.ts
src/store/index.ts
src/store/mutations.ts
src/types/vuetorrent/SortOptions.ts
src/types/vuetorrent/StoreState.ts
tests/unit/__snapshots__/General.spec.ts.snap

Add buttons to import / export settings configuration, UI/UX design might be reworked 😅

feat: Add import / export settings button

---

src/components/Modals/RenameModal.vue
src/services/qbit.ts

perf: Sort tags alphabetically

---

package-lock.json
src/components/Navbar/NavbarActions.vue
src/components/Settings/Tabs/VueTorrent/VGeneral.vue
src/lang/en.json
src/lang/fr.json
src/store/index.ts
src/types/vuetorrent/WebUISettings.ts
tests/unit/__snapshots__/General.spec.ts.snap

perf: Add switch to hide Shutdown button

---

src/views/Settings.vue

Fixes #322 
Issue may be out of date as the top bar isn't fixed but it's done 😄

perf: Scroll to top if tab is changed

---

src/components/Torrent/DesktopCard.vue
src/components/Torrent/Torrent.vue
src/schemas/StoreState.ts

Fix cmd select torrent

---

src/components/Navbar/FilterSelect.vue

perf: Reset selected torrents when changing filters

---

src/helpers.js

perf: Sort files alphabetically in Content tab

---

package-lock.json
src/components/Torrent/DashboardItems/Progress.vue

perf: Fix Progress component sizing on Desktop

---

src/helpers.js
src/types/vuetorrent/TreeObjects.ts

perf: Sort folders before files

---

src/lang/uk.json

chore: Updated Ukrainian translation

---

package-lock.json
src/components/Settings/Tabs/Rss/Feeds.vue
src/lang/en.json

Add a "Refresh All" button to prevent user to click on each button individually

perf: Add Refresh All button for RSS feeds

---

package-lock.json
src/components/Navbar/TransferStats.vue
src/components/Torrent/MobileCard.vue
src/models/Status.ts
src/store/getters.ts

fix: Remove unneeded classes to prevent unexpected color background in MobileCard

---

src/lang/en.json
src/views/RssArticles.vue

perf: Add mark all as read button in RssArticles view

---

src/actions/Torrents.ts
src/lang/en.json
src/store/getters.ts

@Moius @VEWION I'm letting you guys update chinese translations. Keep me updated if it's okay or if you need other tweaks to make it work ^^

perf: Add sum of selected torrents' size to selectedTorrentCountString

---

src/components/Settings/Tabs/Speed.vue
src/lang/zh-hans.json

* fix: modals.settings.speed.scheduler.from and modals.settings.speed.scheduler.to now Can be translated correctly.

Chore: Update simple chinese translation

---

src/components/Navbar/TransferStats.vue

fix: Remove capitalization

---

src/views/RssArticles.vue

perf: add multi-sort support in RSS view

---

src/lang/zh-hans.json
src/lang/zh-hant.json

chore: Update Chinese Translation

chore: Update Chinese Translation

---

src/components/Settings/Tabs/BitTorrent.vue

Please explain what kind of feature your PR's brings or what kind of bug it fixes. Feel free to include screenshots for UI related changes. Keep all the commits inside your PR
related to topic of the PR, otherwise create a seperate PR

fix: invalid v-model for auto add trackers

---

src/components/Settings/Tabs/BitTorrent.vue
src/lang/en.json
tests/unit/__snapshots__/BitTorrent.spec.ts.snap

perf: Add whenSeedingTimeReaches hint

---

src/schemas/StoreState.ts

Forgot to update JSON Schema 😅

chore: Update JSON Schema to import settings with newly added field

---

src/components/Settings/Tabs/BitTorrent.vue
src/components/Settings/Tabs/Connection.vue
src/components/Settings/Tabs/WebUI.vue
src/enums/qbit/AppPreferences.ts

Fix invalid proxy types in settings
Fixes #831

fix: Revert old proxy types

---

src/components/Core/StorageCard.vue
src/components/Core/StringCard.vue
src/components/Navbar/FreeSpace.vue

fix: Navbar capitalisation

---

src/Pages/Dashboard.vue
src/components/Modals/AddModal.vue
src/components/Torrent/TorrentRightClickMenu.vue
src/composables/api/preferences.ts
src/composables/api/torrents.ts
src/composables/validator.ts
src/constants/index.ts
src/plugins/vuetify.ts
src/stores/auth.ts
src/themes/index.ts
src/types/qbit/payloads/AppPreferencesPayload.ts
src/types/qbit/payloads/BasePayload.ts
src/types/qbit/payloads/CreateFeedPayload.ts
src/types/qbit/payloads/QbAddTorrentPayload.ts
src/types/qbit/payloads/QbAppPreferencesPayload.ts
src/types/qbit/payloads/QbBasePayload.ts
src/types/qbit/payloads/QbCreateFeedPayload.ts
src/types/qbit/payloads/QbLoginPayload.ts
src/types/qbit/payloads/QbPeerLogPayload.ts
src/types/qbit/payloads/index.ts

Edit: I'm reopening this PR after a problem forced me to close the previous one.
Allows you to add one or more torrents to the queue via the AddModal.vue component

[Vue 3] Feat: add torrents modal

---

src/models/Torrent.ts
src/views/Dashboard.vue

perf: enable manual sort for priority

---

src/components/Modals/Rss/RuleForm.vue
src/lang/en.json
src/views/Dashboard.vue

perf(rss-rules): Add Select All / None buttons

---

src/components/TorrentDetail/Tabs/Content.vue
src/components/TorrentDetail/Tabs/TorrentTagsAndCategories.vue

Fixes #851 (glitched rename state)
Fix unable to remove tag/category from torrents in dedicated tab

fix: bugs introduced with search engine

---

src/components/Settings/Tabs/Downloads.vue
src/store/getters.ts

fix: Fix size error when deleting torrents under certain conditions

---

src/components/Modals/AddModal.vue

Keep 2 columns on sm+ devices but stack selects on xs devices

perf: Improve responsive design on AddModal

---

src/components/TorrentDetail/Tabs/Info.vue
src/views/TorrentDetail.vue

Adds a watch to repaint canvas

perf: Add hook to repaint piece state canvas on update

---

src/store/getters.ts

Fixes size error patch not working, this time it should be all good 😄 
Fixes #860

fix: size error when deleting torrents under certain conditions

---

src/store/getters.ts

OK, after all this time it should be the last PR to fix this issue 🤞
"TypeError: Reduce of empty array with no initial value"

fix: size error

---

src/components/Navbar/TopActions.vue
src/enums/qbit/LogType.ts
src/lang/en.json
src/router.ts
src/services/qbit.ts
src/styles/styles.scss
src/types/qbit/models/Log.ts
src/types/qbit/models/index.ts
src/views/Logs.vue
src/views/RssArticles.vue

Add button in TopActions to view qBittorrent logs

feat: Add logs view

---

src/components/Modals/AddModal.vue
src/components/Modals/RenameModal.vue
src/components/Modals/Rss/FeedForm.vue
src/components/Modals/Rss/RuleForm.vue
src/components/Modals/SearchPluginManager.vue
src/views/RssArticles.vue
src/views/Settings.vue
src/views/TorrentDetail.vue

chore: Change manual keyboard shortcuts to vue events

---

src/components/Modals/AddModal.vue
src/components/Modals/Rss/FeedForm.vue
src/components/Modals/Rss/RuleForm.vue
src/components/Modals/TagsAndCategories/CreateCategoryDialog.vue
src/components/Modals/TagsAndCategories/CreateTagDialog.vue
src/views/RssArticles.vue
src/views/Settings.vue
src/views/TorrentDetail.vue

Before that, the user had to click inside the component to load the event which is not great. Rolled back only on views as the problem doesn't occur on modals which focuses automatically.
Also removed v-form which reloaded the page instead of sending the request to qbit.

fix: events not working properly on views

---

src/components/TorrentDetail/Tabs/Info.vue

Missed some cleanup to prevent useless api calls, PR was merged too quickly 😅

chore: clean Info

---

src/components/TorrentDetail/Tabs/Info.vue
src/components/TorrentDetail/Tabs/Overview.vue
src/lang/en.json

- Fix incorrect locale key for torrent status
- Move save path from info to overview
- Add torrent file count to overview
- Displays the filename if the torrent only contains 1 file

perf: overview improvements

---

src/components/Modals/Rss/FeedForm.vue
src/store/getters.ts
src/views/Logs.vue
src/views/RssArticles.vue
src/views/SearchEngine.vue
src/views/TorrentDetail.vue

- Fix broken FeedForm keybinds
- Add exception on escape keybind when modals are active

fix: Repair broken keybinds

---

src/components/Modals/ChangeLocationModal.vue
src/components/Modals/RenameModal.vue
src/components/Modals/Rss/FeedForm.vue
src/components/Modals/Rss/RuleForm.vue
src/components/Modals/SearchPluginManager.vue
src/components/Modals/TagsAndCategories/CreateCategoryDialog.vue
src/components/Modals/TagsAndCategories/CreateTagDialog.vue

Add autofocus property on all modals where it was missing.

perf(modals): add autofocus

---

src/components/TorrentDetail/Tabs/Overview.vue

perf(overview): Fixes spacing for tag chips

---

src/components/SearchEngine/SearchTab.vue
src/lang/en.json
src/views/SearchEngine.vue

perf(search): Add tabs + reset results on new search

---

src/components/Torrent/TorrentRightClickMenu.vue
src/mixins/TorrentSelect.ts
src/views/Dashboard.vue

perf(Torrent Card): Highlight torrent card when TRC menu is showed

---

src/components/TorrentDetail/Tabs/Overview.vue
src/lang/en.json
src/lang/zh-hant.json

Add buttons to quickly change torrent location and rename the torrent file when it's the only one selected

perf(overview): Add quick actions buttons

---

src/components/Modals/ChangeLocationModal.vue
src/components/Modals/ConfirmDeleteModal.vue
src/components/Modals/RenameTorrentModal.vue
src/components/Navbar/TopActions.vue
src/components/Torrent/TorrentRightClickMenu.vue
src/views/Dashboard.vue

fix(dashboard): Not able to delete torrent in certain cases

---

src/views/RssArticles.vue

perf(RssArticles): Add clearable property to filter

---

src/App.vue
src/components/Modals/ConfirmDeleteModal.vue
src/components/Settings/Tabs/VueTorrent/VGeneral.vue
src/router.ts
src/store/actions.ts
src/store/mutations.ts
src/types/vuetorrent/StoreState.ts
src/types/vuetorrent/index.ts
src/views/Dashboard.vue
src/views/Login.vue
src/views/MagnetHandler.vue
src/views/Settings.vue
src/views/TorrentDetail.vue

Fixes #995
Also added a fix for the error in dev environment with TorrentProperty

perf: Fixed intervals

---

src/components/TorrentDetail/Tabs/Content.vue

fix(Content): Fix percent progress not displaying properly

---

src/App.vue

When we login to vuetorrent page there is delay in loading torrent. by debugging in network tab found that there is delay of $refreshinterval in calling main data. This PR helps to fix it by adding the fetch maindata to check authentication function
Before 
After
- [*] All Unit tests pass

fixing delayed torrent display on page opening

---

src/views/Logs.vue

fix(logs): Wrong date parsing

---

src/views/Logs.vue

Revert "fix(logs): Wrong date parsing"

---

src/views/Login.vue

perf: Add autofocus on login page

---

package-lock.json
package.json
src/App.vue
src/components/Dashboard/TRC/RightClickMenu.vue
src/components/Dialogs/CategoryFormDialog.vue
src/components/Dialogs/ConfirmDeleteDialog.vue
src/components/Dialogs/ConfirmShutdownDialog.vue
src/components/Dialogs/ConnectionStatusDialog.vue
src/components/Dialogs/MoveTorrentDialog.vue
src/components/Dialogs/MoveTorrentFileDialog.vue
src/components/Dialogs/PluginManagerDialog.vue
src/components/Dialogs/RenameTorrentDialog.vue
src/components/Dialogs/RssFeedDialog.vue
src/components/Dialogs/RssRuleDialog.vue
src/components/Dialogs/TagFormDialog.vue
src/components/Navbar/SideWidgets/BottomActions.vue
src/components/Navbar/TopWidgets/TopContainer.vue
src/components/Settings/RSS/Feeds.vue
src/components/Settings/RSS/Rules.vue
src/components/Settings/TagsAndCategories.vue
src/components/TorrentDetail/Content.vue
src/components/TorrentDetail/Overview.vue
src/composables/Dialog.ts
src/main.ts
src/pages/Dashboard.vue
src/pages/SearchEngine.vue
src/stores/dialog.ts
src/stores/index.ts

⚠️ WIP: still need to convert old dialogs to use new logic ⚠️
EDIT: done

perf(dialog): Rework dialog management to use old generic system

---

src/locales/en.json
src/pages/Dashboard.vue
src/pages/Logs.vue
src/pages/RssArticles.vue

Sort not bound to anything, will add sort composable in another PR 👀

perf(logs): Replace data table with list

---

package-lock.json
package.json
src/components/Dialogs/PluginManagerDialog.vue
src/components/Settings/Downloads.vue
src/pages/SearchEngine.vue

Bump vuetify to latest version and updated code changes which fixed the search download button not working

fix(search): Download button not working

---

package-lock.json
package.json
src/components/Dialogs/CategoryFormDialog.vue
src/components/Dialogs/ConfirmDeleteDialog.vue
src/components/Dialogs/ConfirmShutdownDialog.vue
src/components/Dialogs/ConnectionStatusDialog.vue
src/components/Dialogs/MoveTorrentDialog.vue
src/components/Dialogs/MoveTorrentFileDialog.vue
src/components/Dialogs/PluginManagerDialog.vue
src/components/Dialogs/RenameTorrentDialog.vue
src/components/Dialogs/RssFeedDialog.vue
src/components/Dialogs/RssRuleDialog.vue
src/components/Dialogs/TagFormDialog.vue
src/composables/ArrayPagination.ts
src/composables/index.ts
src/pages/Dashboard.vue
src/pages/Logs.vue
src/pages/RssArticles.vue
src/stores/vuetorrent.ts

Replacing vue-composable by useuse which is maintained and way more complete.
cc @k4lu-0p

perf(composables): Replace vue-composable by vueuse

---

src/locales/en.json

fix(torrent card): Fix incorrect wording

---

src/composables/ArrayPagination.ts

fix(pagination): Fix pageCount not being reactive

---

src/composables/TorrentBuilder.ts

fix(torrent): Use floor instead of round for availability

---

src/pages/Dashboard.vue
src/pages/RssArticles.vue
src/pages/SearchEngine.vue
src/pages/Settings.vue
src/pages/TorrentDetail.vue
src/stores/dashboard.ts
src/stores/dialog.ts

- Added exception on pages when dialogs are active
- Fix Ctrl/Cmd + F not focusing input
- On escape, if search input is visible, hide it, else unselect all torrents

perf(keyboard shortcuts): Improve keybinds

---

README.md
src/helpers/system.ts
src/pages/Dashboard.vue

- Fix cmd key detection on mac devices
- Handle missing focus events on dashboard search input

perf(keybinds): Improve keyboard events

---

src/locales/index.ts
src/locales/locales.ts
src/locales/zh-hans.json

Add Simplified Chinese to the UI interface.

Add Simplified Chinese 添加简体中文

---

src/locales/zh-hans.json

Optimize Simplified Chinese Translation

[fix]Optimize Simplified Chinese Translation 优化简体中文翻译

---

src/components/Dialogs/AddTorrentDialog.vue

perf(AddTorrentDialog): Add loading prop to submit button

---

src/locales/zh-hans.json

I made some vocabulary adjustments to improve the accuracy of the translation.

Fix Simplified Chinese Translation 修正简体中文翻译

---

src/locales/index.ts
src/locales/locales.ts
src/locales/zh-hant.json

chore: Add Traditional Chinese translation

---

src/stores/dashboard.ts
src/stores/maindata.ts

fix(dashboard): Sort not working anymore

---

src/components/Dashboard/Torrent.vue
src/plugins/vuetify.ts

perf(TorrentCard): Darken selected item background

---

src/App.vue

fix(AddTorrent): Error while accessing preferences

---

src/components/DnDZone.vue

fix(settings): Add DnD exception on settings page

---

src/pages/Dashboard.vue

fix(dashboard): Take filters into account when selecting all torrents

---

src/App.vue
src/pages/Login.vue
src/stores/vuetorrent.ts

Feature wasn't ported to the latest version. This should add it back 😄 
#1108

perf(login): Add login with query params

---

src/components/Settings/VueTorrent/DashboardItem.vue
src/components/Settings/VueTorrent/TorrentCard.vue

perf(TorrentCard): Only process drag on handle

---

src/stores/vuetorrent.ts

fix(TorrentCard): Fix properties not being persisted

---

src/components/Dashboard/Torrent.vue

perf(Torrent): Wrap title

---

index.html
src/components/Navbar/SideWidgets/FilterSelect.vue
src/components/Navbar/TopWidgets/ActiveFilters.vue
src/composables/SearchQuery.ts
src/pages/Dashboard.vue
src/plugins/vuetify.ts
src/stores/dashboard.ts
src/stores/maindata.ts

Enabled version:
Disabled version:

feat(filters): Allow to disable filters temporarily

---

src/components/Settings/VueTorrent/General.vue
src/constants/vuetorrent/TitleOptions.ts
src/constants/vuetorrent/index.ts
src/locales/en.json
src/stores/vuetorrent.ts

feat(title): Ability to set custom browser tab title

---

src/pages/Dashboard.vue

#1266 search shortcut regression fix
Please explain what kind of feature your PR's brings or what kind of bug it fixes. Feel free to include screenshots for UI related changes. Keep all the commits inside your PR
related to topic of the PR, otherwise create a seperate PR. Don't forget to link the related issue! (if applicable)

#1266 search shortcut

---

src/components/Settings/VueTorrent/TorrentCard.vue

fix(settings): Update drag handling to completed properties

---

src/components/Settings/VueTorrent/General.vue
src/pages/MagnetHandler.vue

perf(MagnetHandler): Open add dialog on magnet link

---

src/components/Navbar/Navbar.vue

fix(Navbar): Add missing bind on right drawer setting

---

src/components/Dialogs/AddTorrentDialog.vue
src/components/Settings/Advanced.vue
src/components/Settings/Behavior.vue
src/components/Settings/BitTorrent.vue
src/components/Settings/Connection.vue
src/components/Settings/Downloads.vue
src/constants/qbit/AppPreferences.ts
src/pages/Settings.vue
src/types/qbit/models/AppPreferences.ts
src/types/qbit/models/ServerState.ts
src/types/qbit/payloads/AddTorrentPayload.ts

feat(preferences): Update settings page to include missing preferences

---

src/components/Settings/BitTorrent.vue

fix(settings): Update disabled state in Bittorrent tab

---

src/components/Dashboard/Torrent.vue
src/pages/Dashboard.vue
src/stores/dashboard.ts
src/stores/maindata.ts

fix(dashboard): Fix span selection not using filters

---

src/components/Dialogs/ConnectionStatusDialog.vue

feat(ConnectionStatusDialog): Add DHT node and active peer connections

---

src/pages/Login.vue

Fix authentication race condition (#1285)

---

src/App.vue
src/components/AddPanel.vue
src/components/Dashboard/TRC/RightClickMenuEntry.vue
src/components/Dialogs/AddTorrentDialog.vue
src/components/DnDZone.vue
src/components/Navbar/TopWidgets/TopContainer.vue
src/constants/qbit/TorrentOperatingMode.ts
src/constants/qbit/index.ts
src/pages/MagnetHandler.vue
src/pages/RssArticles.vue
src/pages/SearchEngine.vue
src/stores/addTorrents.ts
src/stores/maindata.ts
src/stores/navbar.ts
src/types/qbit/models/AppPreferences.ts
src/types/qbit/models/FeedRule.ts
src/types/qbit/payloads/AddTorrentPayload.ts

Still some testing to do on these new fields.
Fixes #1320

feat(AddTorrentDialog): Rework dialog to add missing parameters

---

src/components/Dashboard/TRC/RightClickMenu.vue
src/components/Dialogs/ShareLimitDialog.vue
src/components/Dialogs/SpeedLimitDialog.vue

fix(TRC): Use all selected torrents for transfer limits

---

src/components/Dialogs/AddTorrentDialog.vue

perf(AddTorrentDialog): Add autocomplete attribute

---

src/components/Settings/Speed.vue

fix(Settings/Speed): Fix speed values conversion

---

src/components/TorrentDetail/Content.vue
src/components/TorrentDetail/Content/FileNode.vue
src/components/TorrentDetail/Content/FolderNode.vue
src/components/TorrentDetail/Content/RootNode.vue
src/components/TorrentDetail/Overview.vue
src/pages/Logs.vue

feat(Content): Add menu to set file priority

---

src/components/TorrentDetail/Overview.vue

- 's' key to move (savePath)
- 'f' key to rename file (quick rename)

feat(Overview): Add keyboard shortcuts

---

src/components/Settings/Advanced.vue

fix(Advanced): Network interfaces doesn't fill properly

---

src/components/Navbar/SideWidgets/FreeSpace.vue
src/components/Navbar/SideWidgets/SpeedGraph.vue
src/components/Navbar/SideWidgets/TransferStats.vue
src/components/Settings/Behavior.vue
src/components/Settings/Connection.vue
src/components/Settings/VueTorrent/General.vue
src/pages/Settings.vue

perf(localization): Add missing keys to Tolgee

---

src/pages/Settings.vue
src/pages/TorrentDetail.vue

fix(tabs): Remove swipe gestures

---

src/components/DnDZone.vue

perf(DnDZone): Open add dialog on drop

---

src/components/Core/HistoryField.vue
src/services/qbit.ts

fix(AddTorrentDialog): Fix falsy values not sent to qbit

---

src/components/Dashboard/DashboardItems/ItemChip.vue
src/components/Dashboard/Views/Table/DashboardItems/ItemChip.vue
src/components/Settings/VueTorrent/General.vue
src/locales/en.json
src/pages/Dashboard.vue
src/stores/vuetorrent.ts

feat(Chips): Add option to hide values if empty

---

package.json
write-version.cjs

chore: Add version.txt in build

---

src/stores/navbar.ts

perf(SpeedGraph): Init values with null

---

README.md
src/components/Dialogs/AddTorrentDialog.vue
src/components/Dialogs/RssFeedDialog.vue
src/locales/en.json
src/pages/RssArticles.vue
src/services/qbit.ts
src/stores/rss.ts

feat(RSS): Allow edit feed URL (4.6.0+)

---

src/components/Dashboard/TRC/RightClickMenu.vue
src/components/TorrentDetail/Overview.vue
src/locales/en.json

fix(clipboard): Add missing toast on clipboard action

---

src/components/Core/PasswordField.vue
src/pages/Login.vue

perf(accessibility): Add name attributes to login form

---

index.html
package-lock.json
package.json
public/manifest.webmanifest
public/registerSW.js
public/sw.js
vite.config.ts

perf(PWA): Use Network-only strategy for service worker

---

package-lock.json

This reverts commit 1dcfdb2d which breaks right click children behaviour

fix(RightClick): Fix children behaviour not working

---

src/components/Core/DataCard.vue
src/components/Core/SpeedCard.vue
src/components/Core/StringCard.vue
src/components/Dashboard/Toolbar.vue
src/components/Navbar/Navbar.vue
src/components/TorrentDetail/Info.vue
src/components/TorrentDetail/Peers.vue
src/pages/Logs.vue
src/pages/SearchEngine.vue
src/pages/TorrentDetail.vue
src/styles/styles.scss

Following discussions on the discord, this PR updates static text fields (without interaction) to make them selectable.

UI text improvements

---

src/components/Dashboard/Views/Table/DashboardItems/ItemPercent.vue

fix(progress): Remove striping on table view

---

__mocks__/torrents.json
src/components/Dialogs/ImportSettingsDialog.vue

fix(import): Update field validation to prevent false negative

---

src/pages/Login.vue

perf(autofill): Add valid id on login fields

---

src/components/TorrentDetail/Peers.vue

fix(preferences): Update banned IP field when banning from the Peers tab

---

src/components/TorrentDetail/Peers.vue

fix(Peers): Wrap IPv6 to display ban button

---

src/components/Settings/VueTorrent/General.vue

fix(settings): Infinite scroll value not recognized

---

src/stores/content.ts

fix(content): Fix file list not loading

---

src/components/TorrentDetail/Content/Content.vue
src/components/TorrentDetail/Overview.vue
src/pages/TorrentDetail.vue
src/stores/content.ts

perf(TorrentDetail): Reduce API calls by centralizing files data

---

.github/CONTRIBUTING.md

This PR is an initiative to improve [Community Standards](https://github.com/VueTorrent/VueTorrent/community) and to promote contributions as an open-source project.

chore: Add contribution guidelines

---

package-lock.json
package.json
vite.config.ts

fix: support lower version browsers with top level await

---

.github/FUNDING.yml

This PR is an initiative to improve [Community Standards](https://github.com/VueTorrent/VueTorrent/community) and to promote funding
From [Displaying a sponsor button in your repository](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository)

chore: Add sponsor button

---

src/components/TorrentDetail/PieceCanvas.vue

* `Application` will crash if `ref` is applied, use `shallowRef`
* Add promise around `Application` to ensure init finishes before being used
* Add rudimentary guard boolean to prevent `renderCanvas` from running concurrently

TorrentDetail/PieceCanvas Fix [fix]

---

src/pages/SearchEngine.vue

perf(SearchEngine): Add description link

---

src/components/Dashboard/DashboardItems/ItemText.vue
src/components/Dashboard/Views/Table/DashboardItems/ItemText.vue
src/constants/vuetorrent/DashboardDefaults.ts
src/plugins/vuetify.ts

Fixes #1562
[Color source](https://github.com/CallMeBruce/nightwalker/blob/2301b1cc436d802abe1e2cb6f132dff12e40157b/private/css/nightwalker.css#L14-L17)
[Threshold values source](https://github.com/CallMeBruce/nightwalker/blob/2301b1cc436d802abe1e2cb6f132dff12e40157b/private/scripts/dynamicTable.js#L1223-L1238)
| List / Grid | Table |
| ----------- | ----- |
| ![image](https://github.com/VueTorrent/VueTorrent/assets/22910497/cac81880-8bae-4445-af79-10975d22be29) | ![image](https://github.com/VueTorrent/VueTorrent/assets/22910497/82c77ae6-b8fe-4779-881b-31756eb64780) |

perf: Add ratio colors

---

.github/workflows/build-release.yml

[source link](https://github.com/SethCohen/github-releases-to-discord?tab=readme-ov-file)

chore(discord): Switch to changelog notification

---

CHANGELOG.md
src/components/Dashboard/DashboardItems/ItemText.vue
src/components/Dashboard/Views/Table/DashboardItems/ItemText.vue
src/components/Navbar/Navbar.vue
src/constants/vuetorrent/DashboardDefaults.ts

Not sure if I can speak for everyone, but I found it annoying that clicking the title while viewing torrent details or webui settings doesn't route you back to the homescreen. This pr fixes that.
If anyone has any issues with the implementation/styling of this, please let me know :)

perf: add title navigation

---

src/components/Dashboard/DashboardItems/ItemChip.vue
src/components/Dashboard/Views/Table/DashboardItems/ItemChip.vue
src/components/Settings/VueTorrent/General.vue
src/locales/en.json
src/stores/vuetorrent.ts

perf(chip colors): Add feature toggle

---

src/components/Settings/Advanced.vue

fix: announced IP not correctly parsed

---

src/components/Settings/VueTorrent/TorrentCard/Grid.vue
src/components/Settings/VueTorrent/TorrentCard/List.vue
src/components/Settings/VueTorrent/TorrentCard/Table.vue

Add ability to select/deselect all card items in 1 click.

perf(torrentCard): Add select all / none buttons

---

src/components/Dashboard/DashboardItems/ItemChip.vue

make small chip label to better apperence

perf(TorrentCard): decrease chip size

---

src/components/Dashboard/Views/Table/DashboardItems/ItemChip.vue

extra patch for https://github.com/VueTorrent/VueTorrent/pull/1608

perf(TorrentCard): decrease chip size for table view

---

src/components/TorrentDetail/Content/ContentNode.vue
src/composables/TreeBuilder.ts
src/stores/content.ts

fix(TorrentDetail): Differentiate fullName for the root node(#1616)

---

src/components/Dialogs/RssRuleDialog.vue

fix(RSS Rules): Fix last match not displaying

---

src/components/Settings/RSS/Rules.vue
src/services/QbitProvider.ts
src/stores/rss.ts
src/types/qbit/models/FeedRule.ts
src/types/qbit/models/index.ts

fix(RSS Rules): Include deprecated fields for better retro-compatibility

---

src/components/Dialogs/AddTorrentParamsForm.vue

fix(RSS Rules): Download limits not sent correctly to qbit

---

src/components/Settings/VueTorrent/General.vue
src/constants/vuetorrent/DashboardDefaults.ts
src/locales/en.json
src/stores/vuetorrent.ts

perf(ratio colors): Add feature toggle

---

src/constants/vuetorrent/DashboardDefaults.ts

Introduced with fb1a855f70194e98eb4d517139e048769d4df7f5
Fixes #1630

fix: seeds and peers shows same value

---

src/components/Settings/WebUI.vue

fix(WebUI): Bypass auth subnet whitelist not working

---

src/components/Dashboard/DashboardItems/ItemDuration.vue
src/components/Dashboard/Views/Table/DashboardItems/ItemDuration.vue
src/components/Dialogs/AddTorrentParamsForm.vue
src/components/TorrentDetail/Info/PanelDuration.vue
src/components/TorrentDetail/Info/PanelText.vue
src/constants/vuetorrent/DashboardDefaults.ts
src/constants/vuetorrent/DashboardProperty.ts
src/locales/en.json

fix(AddTorrentParams): Convert seeding time to minutes manually

---

src/components/Dashboard/DashboardItems/ItemDuration.vue
src/components/Dashboard/Views/Table/DashboardItems/ItemDuration.vue
src/components/Dialogs/AddTorrentParamsForm.vue
src/components/TorrentDetail/Info/PanelDuration.vue
src/constants/vuetorrent/DashboardDefaults.ts

This time it really fixes #1648

fix(share limits): Revert and fix display

---

src/App.vue
src/pages/MagnetHandler.vue
src/pages/index.ts

fix(MagnetHandler): Don't show add dialog if not authenticated

---

src/locales/en.json

perf: Reword torrent priority to queue position

---

src/components/Settings/VueTorrent/General.vue

perf(settings): Prettify exported JSON

---

src/components/AddPanel.vue
src/components/Dashboard/DashboardItems/ItemChip.vue
src/components/Dashboard/Views/Grid/GridTorrent.vue
src/components/Dashboard/Views/List/ListTorrent.vue
src/components/Dashboard/Views/Table/DashboardItems/ItemChip.vue
src/components/Dashboard/Views/Table/TableView.vue
src/components/Dialogs/BulkRenameFilesDialog.vue
src/components/Dialogs/ConfirmDeleteDialog.vue
src/components/Navbar/Navbar.vue
src/components/Navbar/SideWidgets/TransferStats.vue
src/components/Navbar/TopWidgets/ActiveFilters.vue
src/components/TorrentDetail/Peers.vue
src/components/TorrentDetail/Trackers.vue
src/locales/en.json
src/services/qbit/IProvider.ts
src/services/qbit/MockProvider.ts
src/services/qbit/QbitProvider.ts
src/stores/maindata.ts
src/styles/styles.scss
src/types/qbit/models/Peer.ts
src/types/qbit/responses/TorrentPeersResponse.ts

perf(Peers): Switch to data table

---

src/composables/TreeBuilder.ts
src/types/qbit/models/TorrentFile.ts
src/types/vuetorrent/TreeObjects.spec.ts
src/types/vuetorrent/TreeObjects.ts

fix(content): Fix files not rendering under certain conditions

---

src/components/Core/ColoredChip.spec.ts
src/components/Core/ColoredChip.vue
src/components/Dashboard/DashboardItems/ItemChip.vue
src/components/Dashboard/Views/Table/DashboardItems/ItemChip.vue
src/components/TorrentDetail/Overview.vue

fix(chips): Use text instead of invisible pill

---

src/composables/TreeBuilder.ts

Fixes https://github.com/VueTorrent/VueTorrent/security/code-scanning/4

fix(content): Improve Windows path support

---

.github/workflows/codeql-analysis.yml

From https://docs.github.com/en/code-security/code-scanning/creating-an-advanced-setup-for-code-scanning/customizing-your-advanced-setup-for-code-scanning#specifying-directories-to-scan

chore: Add CodeQL scan on PRs

---

src/components/TorrentDetail/PieceCanvas.vue
src/stores/content.ts
src/stores/logs.ts
src/stores/maindata.ts
vite.config.ts

Also include a fix for vite proxy to better handle reverse proxy, PR will be rebased instead of squashed.

fix(content): Prevent app from freezing when exiting too quickly

---

README.md
src/components/Settings/addons/EnhancedEdition.vue
src/locales/en.json
src/pages/Settings.vue
src/services/qbit/MockProvider.ts
src/types/qbit/models/AppPreferences.ts

feat(addons): Add qbit Enhanced edition support

---

.github/workflows/build-release.yml
Dockerfile

Create official linuxserver docker mod image

feat(docker): Add official LSIO mod docker image to pipeline

---

src/constants/vuetorrent/Comparators.ts

fix(Dashboard): Name sorting not working

---

src/components/Dialogs/BulkRenameFilesDialog.vue
src/components/TorrentDetail/Overview.vue
src/pages/TorrentDetail.vue
src/stores/content.ts

fix(Overview): Filename not refreshing after rename

---

src/stores/maindata.ts

fix(Dashboard): torrents not removed from local cache

---

src/stores/categories.ts
src/stores/tags.ts
src/stores/torrents.ts

Caused by #1762
Same bug than c05776cceb9e2281be340d39078890f989eab2fa
Fixed for categories, tags, torrents and trackers to prevent further issues

fix(Dashboard): Clean removed data from local cache

---

src/components/TorrentDetail/Content/ContentNode.vue
src/stores/content.ts
src/types/vuetorrent/TreeObjects.spec.ts
src/types/vuetorrent/TreeObjects.ts

- Improve concurrency of updateFileTree
- Fix selection toggle **enabling** all files on mixed priority
- Fix mixed priority folder render (checkbox / color)
- Only display selected size on folders

fix(content): Fix regressions after #1779

---

package-lock.json
package.json
src/components/Dashboard/RightClick.vue

Fixes #1741
Build size increased of about 100 kB with new dep for handling zip in memory.

feat(export): Zip files when exporting several torrents

---

src/components/Dialogs/ContentFilterDialog.vue
src/components/Dialogs/dialog.vue.template
src/components/TorrentDetail/Content/Content.vue
src/helpers/path.spec.ts
src/helpers/path.ts
src/locales/en.json
src/services/qbit/MockProvider.ts
src/stores/content.ts

#1173
This PR creates a new dialog that allows the user to bulk select files for a torrent.

perf(content): Add bulk selection using filters

---

src/components/TorrentDetail/Content/Content.vue
src/components/TorrentDetail/Content/ContentNode.vue
src/composables/TreeBuilder.ts
src/main.ts
src/stores/categories.ts
src/stores/content.ts
src/stores/maindata.ts
src/stores/tags.ts
src/stores/torrents.ts
src/stores/trackers.ts

perf: Drastically increase performance on dashboard and content view

---

src/components/Dashboard/RightClick.vue
src/components/TorrentDetail/Overview.vue

perf: Disable copy action if context not secure

---

src/stores/navbar.ts

perf: Increase mobile threshold for initial navbar open status

---

src/stores/addTorrents.ts
src/stores/app.ts
src/stores/categories.ts
src/stores/content.ts
src/stores/dashboard.ts
src/stores/dialog.ts
src/stores/history.ts
src/stores/logs.ts
src/stores/maindata.ts
src/stores/navbar.ts
src/stores/preferences.ts
src/stores/rss.ts
src/stores/searchEngine.ts
src/stores/tags.ts
src/stores/torrentDetail.ts
src/stores/torrents.ts
src/stores/trackers.ts
src/stores/vuetorrent.ts

From [pinia doc](https://pinia.vuejs.org/cookbook/hot-module-replacement.html)

chore: Introduce HMR in stores

---

src/components/Core/SpeedCard.vue
src/components/Navbar/SideWidgets/CurrentSpeed.vue
src/components/Navbar/SideWidgets/SpeedGraph.vue
src/components/Settings/VueTorrent/General.vue
src/locales/en.json
src/services/qbit/MockProvider.ts
src/stores/vuetorrent.ts
src/themes/global.ts

Fixes #1726
@Seros
Here's my shot at adding the speed limits to the UI, lmk what you think.

perf: Display speed limits in navbar

---

package-lock.json
package.json
src/components/Dashboard/RightClick.vue
src/components/Dialogs/AddTorrentParamsForm.vue
src/components/Navbar/SideWidgets/FilterSelect.vue
src/components/Settings/TagsAndCategories.vue
src/components/TorrentDetail/TagsAndCategories.vue
src/helpers/datetime.spec.ts
src/pages/SearchEngine.vue
src/services/qbit/MockProvider.ts
src/stores/categories.ts
src/stores/tags.ts
src/stores/trackers.ts

fix: Sort values correctly

---

src/components/TorrentDetail/Peers.vue
src/components/TorrentDetail/Trackers.vue
src/locales/en.json
src/pages/Logs.vue
src/services/qbit/MockProvider.ts
src/stores/logs.ts

perf(trackers): Switch to table view

---

src/stores/navbar.ts

perf(navbar): Persist opened state between sessions

---

src/components/Dashboard/Toolbar.vue
src/pages/Dashboard.vue
src/stores/dashboard.ts

perf(Dashboard): Merge pagination in toolbar on desktop

---

src/components/Dashboard/Toolbar.vue
src/components/Dashboard/Views/Table/TableView.vue
src/constants/vuetorrent/DashboardDefaults.ts

perf(TableView): Allow click on headers for quick sort

---

src/pages/SearchEngine.vue
src/stores/searchEngine.ts
src/types/vuetorrent/SearchData.ts

Use last query text instead of query field value.

perf(SearchEngine): Use last query as tab title

---

src/components/Dashboard/Views/Table/Header.vue
src/components/Dashboard/Views/Table/TableView.vue

chore(TableView): Add missing sort on title header

---

src/stores/trackers.ts

perf(trackers): Use hostname instead of full URL

---

src/components/Dashboard/Toolbar.vue

perf(Dashboard): Improve "sort by" keyboard interaction

---

src/components/Dialogs/ContentFilterDialog.vue

- Sort extensions in dropdown
- Close dialog on include / exclude

perf(Content/bulk select): Improve UX

---

src/stores/tags.ts

fix: Remove latest Set methods usage

---

.github/workflows/build-release.yml

See [CI run](https://github.com/VueTorrent/VueTorrent/actions/runs/10346089587/job/28634121561#step:6:262)

chore: Fix workflow warning

---

src/helpers/datetime.ts

fix(ETA): Update incorrect max value

---

src/components/Navbar/SideWidgets/FilterSelect.vue
src/components/Settings/VueTorrent/General.vue
src/constants/vuetorrent/FilterType.ts
src/constants/vuetorrent/index.ts
src/locales/en.json
src/stores/torrents.ts
src/stores/vuetorrent.ts

feat(filters): Add conjunctive / disjunctive filter type

---

package-lock.json
package.json

chore(eslint): Rollback version bump

---

src/components/Dashboard/Views/Table/TableView.vue
src/styles/styles.scss

fix(TableView): Ripple effect on safari

---

.github/workflows/build-release.yml
.github/workflows/test.yml
write-version.cjs

Prepare environment for upcoming backend update to allow for latest version detection of nightly builds.

chore(CI): Create nightly pre-release job

---

src/pages/index.ts

Prevent empty page if URL doesn't exists. Redirects to the dashboard page.

perf: Add catch-all route

---

src/pages/Login.vue
src/services/qbit/IProvider.ts
src/services/qbit/MockProvider.ts
src/services/qbit/QbitProvider.ts
src/stores/app.ts

Include status code and response body for easier debugging of the root cause

perf(Login): Improve error message

---

docker-compose.yml

Remove deprecated commented backend service
Add docker mod for the easiest standalone setup

chore: Update docker-compose.yml

---

src/App.vue
src/pages/Settings.vue
src/services/backend.ts

fix(backend): Update toast condition when backend unreachable

---

src/services/qbit/QbitProvider.ts

fix(RSS): Fix mark as read on single article

---

src/components/Core/RightClickMenu/RightClickMenu.vue
src/components/Core/RightClickMenu/RightClickMenuEntry.vue
src/components/Dashboard/RightClick.vue
src/types/vuetorrent/RightClickMenuEntryType.ts
src/types/vuetorrent/index.ts

Bug reported on Discord
Caused by the dividers messing with the virtual scroller calculations

fix(RightClick): Handle issue where certain bottom values would not render

---

src/stores/torrents.ts

fix(ActiveFilters): Force-enable filter after clear

---

src/components/Dialogs/AddTorrentParamsForm.vue

fix(AddTorrents): Don't override savePath on empty category savePath

---

src/pages/Logs.vue
src/stores/logs.ts

fix(Logs): Persist filters in localStorage

---

src/components/Dialogs/ConnectionStatusDialog.vue
src/components/Settings/VueTorrent/General.vue
src/locales/en.json
src/stores/logs.ts
src/stores/vuetorrent.ts

Default is opt-out to prevent leaking external IP

feat: Only fetch external IP data if enabled

---

src/pages/SearchEngine.vue

fix(SearchEngine): Fix broken category list

---

src/pages/SearchEngine.vue

fix(SearchEngine): Sort plugins by name

---

src/components/TorrentDetail/Content/Content.vue
src/components/TorrentDetail/Content/ContentNode.vue
src/stores/content.ts

- Up / Down arrows: move up and down
- Left / Right arrow: Collapse / Expand folder
- Spacebar: Toggle selection (Normal / Unwanted)
When moving selection using keyboard, view centers on the selected element.

feat(Content): Handle keyboard inputs

---

src/components/TorrentDetail/Content/Content.vue

chore(content): Prevent event conflict when filter input is focused

---

src/components/Settings/Advanced.vue
src/constants/qbit/AppPreferences.ts
src/locales/en.json

fix(Settings/Advanced): Add missing disk IO type

---

src/components/Navbar/SideWidgets/FilterSelect.vue
src/stores/torrents.ts

feat(filters): Add torrent count for each filter values

---

src/components/Dashboard/RightClick.vue
src/components/Navbar/SideWidgets/FilterSelect.vue
src/components/Settings/TagsAndCategories.vue
src/locales/en.json
src/stores/categories.ts
src/stores/tags.ts
src/stores/torrents.ts

Available in right click menu and in Settings > Tags And Categories

feat: Add remove unused tags/categories actions

---

src/stores/torrents.ts

fix(trackers): Update "Untracked" filter matching

---

src/stores/maindata.ts

fix(selection): Filter out torrents not matching filters

---

src/components/RSS/Feeds/Article.vue
src/locales/en.json
src/pages/RssArticles.vue

perf(RSS): Add "new" chip for increased contrast

---

src/stores/torrents.ts

fix(filters): Prevent re-enable on app launch

---

src/components/Navbar/SideWidgets/FilterSelect.vue
src/components/Navbar/TopWidgets/ActiveFilters.vue
src/components/TorrentDetail/Trackers.vue
src/constants/vuetorrent/TrackerSpecialFilter.ts
src/constants/vuetorrent/index.ts
src/locales/en.json
src/services/qbit/MockProvider.ts
src/stores/torrents.ts

perf(filters): Differentiate "Untracked" and "Not working" trackers

---

src/pages/SearchEngine.vue

perf(SearchEngine): Update mobile variant to be more compact

---

src/components/Dialogs/TorrentCreatorFormDialog.vue
src/locales/en.json
src/pages/TorrentCreator.vue
src/types/qbit/models/TorrentCreatorParams.ts
src/types/qbit/models/TorrentCreatorTask.ts

fix(TorrentCreator): Add source field for qbit 5.0.3+

---

src/components/TorrentDetail/Content/ContentNode.vue
src/composables/TreeBuilder.ts
src/pages/TorrentDetail.vue
src/stores/content.ts

feat(Content): Add expand / collapse all actions to right-click menu

---

src/composables/BackendSync.ts
src/pages/TorrentDetail.vue
src/stores/torrentDetail.ts

perf(TorrentDetail): Persist last opened tab

---

src/components/TorrentDetail/Content/Content.vue
src/pages/TorrentDetail.vue
src/stores/content.ts

fix(Content): Tree not expanding on load

---

src/components/RSS/Feeds/FeedList.vue
src/services/qbit/MockProvider.ts

Display all feeds even if articles empty for editing or deletion

fix(RSS): Display all feeds even if articles empty

---

src/stores/logs.ts

https://github.com/VueTorrent/VueTorrent/blob/098ee25593ff1a483999e3b67bab68dc5a97a278/src/pages/Logs.vue#L75
https://github.com/VueTorrent/VueTorrent/blob/098ee25593ff1a483999e3b67bab68dc5a97a278/src/App.vue#L83

fix(Logs): Prevent duplication on page refresh

---

src/components/Dashboard/Toolbar.vue
src/components/Dashboard/Views/Grid/GridView.vue
src/components/Dashboard/Views/List/ListView.vue
src/components/Dashboard/Views/Table/TableTorrent.vue
src/components/Dashboard/Views/Table/TableView.vue
src/components/Settings/VueTorrent/General.vue
src/constants/vuetorrent/PaginationPosition.ts
src/constants/vuetorrent/index.ts
src/locales/en.json
src/pages/Dashboard.vue
src/stores/vuetorrent.ts

perf(Dashboard): Make scroll bars always visible

---

src/App.vue
src/composables/BackendSync.ts

Fixes VueTorrent/vuetorrent-backend#57

perf(backend): Sync display mode and sort

---

src/pages/Dashboard.vue

fix(Dashboard): Remove empty space when pagination is hidden

---

src/components/Settings/Downloads.vue
src/constants/qbit/AppPreferences.ts
src/locales/en.json
src/types/qbit/models/AppPreferences.ts

fix(Settings): Update "delete torrent files afterwards" not working

---

src/components/Settings/Advanced.vue

fix(Settings/Advanced): Update unit conversions

---

src/App.vue
src/components/Dialogs/AddTorrentDialog.vue
src/components/DnDZone.vue
src/pages/MagnetHandler.vue
src/stores/addTorrents.ts

Also improved init mechanism to reduce complexity

fix(AddTorrentDialog): Remove default value for speed limits

---

src/components/Navbar/SideWidgets/SpeedGraph.vue

Fixes #2173
Set fixed tooltip to prevent overflow

fix(SpeedGraph): Set fixed tooltip

---

src/components/Dialogs/BulkRenameFilesDialog.vue
src/components/Dialogs/ContentFilterDialog.vue
src/components/TorrentDetail/Content/ContentNode.vue
src/constants/vuetorrent/FileIcon.ts
src/constants/vuetorrent/index.ts
src/helpers/index.ts
src/helpers/path.spec.ts
src/helpers/path.ts
src/locales/en.json

This uses the same map as for the file icons. Maps have been reworked and extended with more types

feat(Content/Filter): Group extensions of same type

---

src/App.vue
src/services/qbit/MockProvider.ts

#2097
I hope it's enough now.
localhost qbittorrent responded in 46ms, tested with 1ms with mock and it still works.

fix: "Checking auth status" toast
