VueTorrent/VueTorrent

package-lock.json, package.json, src/components/Modals/AddModal.vue
- Added a checkbox in the add torrent modal to allow users that upload content skip the file hash check
- Set as false the autoTMM param to download the torrent into the specified path
- Added a combobox to select the torrent category on adding
=> Improvements on AddModal

src/components/Navbar/FilterSelect.vue
Update typo from `Erorred` to `Errored`.
=> Typo in sidebar filter

src/store/index.js
Using docker linuxserver/qbittorrent:latest, queried version 4.3.2
```
root@d60a614b4c8d:/# qbittorrent-nox -v
qBittorrent v4.3.2
```
the `/info` API: `/api/v2/torrents/info?sort=default&reverse=true&hashes=&filter=all`
returns:
400 `'sort' parameter is invalid`
So I fixed the App default value with one that exists in the API, as their documentation tells
> They can be sorted using any field of the response's JSON array
"default" is not a valid one, to have a default, we should **omit** the sort parameter altogether
**edit**: I added another commit to omit the sort parameter as default 😉
=> valid sort options default for /info API

src/views/Dashboard.vue
- Fixed white line below pagination that is visible in dark theme mode
Before
After
Also verified for mobile view. Looks OK.
=> Fixed white line below pagination that is visible in dark theme mode

src/models/Torrent.js
- fixed forceDL misspelling that caused forced downloading torrents to display as Failed
- added identification for forced for both downloading and uploading torrents
=> Fixed forceDL misspeling that caused forced downloading torrents to be displayed as Failed

src/store/index.js, vue.config.js
Adds `Uploaded` property to torrent and changes ordering.
Adds `QBITTORRENT_PORT` and `VUETORRENT_PORT` for development. Defaults to original ports, but if developer has different ports, this is useful without changing code.
=> feat: add uploaded property

src/components/Core/SpeedCard.vue
Current speed cards redesign
- current speed cards redesign
=> feat: current speed cards redesign

src/components/Modals/SpeedLimitModal.vue
- long strange floating number on initialization when speed was unlimited
- autoselecting value on modal open so you can immediately start setting correct limit without moving the mouse to it 
- firing submit on `Enter` in the text field
=> feat: improved per-torrent speed limits modal

src/components/Modals/TorrentDetailModal/Tabs/Info.vue
- added infinity sign instead of None for unlimited speeds in torrent detail modal
- space in units for upload/download speed limit in torrent info modal
=> feat: torrent detail infinity sign for unlimited speeds

src/components/Modals/SettingsModal/SettingsModal.vue, src/components/Modals/SettingsModal/Tabs/VueTorrent.vue, src/components/Modals/TorrentDetailModal/TorrentDetailModal.vue, src/mixins/Modal.js
When using a mobile device, a malfunction occurs due to the gesture function.
changing the order of items on the dashboard, the item is not removed from the screen when the item is drop, but is displayed in a superimposed manner.
and It can't use any horizontal scrolling on the 'torrent detail' page.
- A fatal gesture error occurs in draggable items or horizontal scrolling by the built-in gesture.
=> remove gesture feature on tabs

src/App.vue
Use `process.env` for version instead of importing `package.json`. Completely unnecessary, but something I learned recently and could be better practice?
=> chore: use process.env for version

package-lock.json, src/App.vue, vue.config.js
Currently, when webpack bundles the Vue application, it no longer has access to `process.env`. I've updated the webpack plugins to include this in the build and the application now has access to the value.
Ref: https://github.com/WDaan/VueTorrent/pull/212
I tested putting via `npm run serve` as well as `npm run build` and using it like we would in production. In both cases, seemed to be working fine!
=> fix: application version getter

src/components/Navbar/ConnectionStatus.vue, src/components/Navbar/NavbarActions.vue
Hey, thanks for a great project! Some time ago I was thinking about building alternative UI using the same stack, but when I found yours it was clear enough that there is no sense doing that.
Recently I was doing some network setup changes and found this little feature to be really missing - showing if connection port is open. To check that I had to use default web UI for some time, which, you know, is not the best experience :smile:. So here is my 5 cents and hopefully more to come.
4 icons will be shown for 4 states: _connected, disconnected, firewalled_ and when there is no status data, with a tooltip. Hopefully the placement is ok.
Please find screenshots below (all states on desktop + mobile view):
=> Show connection status at the bottom of Navbar

.github/workflows/release.yml, package-lock.json, src/components/Modals/SettingsModal/Tabs/Vuetorrent/General.vue, src/components/Modals/ShareLimit/ShareLimitInput.vue, src/components/Modals/ShareLimit/ShareLimitModal.vue, src/components/Modals/ShareLimitModal.vue, src/components/Modals/SortModal.vue, src/components/Modals/TorrentDetailModal/Tabs/Info.vue, src/filters.js, src/models/Torrent.js, src/styles/styles.scss
=> perf: better share limit modal

src/lang/id.js
I have added Indonesian language
=> perf: add Indonesian

README.md, public/index.html, src/actions/DocumentTitle.js, src/components/Navbar/Navbar.vue
=> fix: spelling mistake in README and "qBittorrent" casing

src/lang/es.js
Saw that this awesome WebUI doesn't have Spanis traslation! so i added it.
Sorry for my bad english :)
=> perf: add Spanish Language

src/styles/styles.scss
Links with `a` tags have low visibility when using the dark theme.
=> fix: low visibility text in dark theme

src/components/Modals/SearchModal/SearchModal.vue, src/services/qbit.js
Search results are not visible until user stops the search. This behavior is different from desktop clients.
Also, search always returns 50 total results no matter what.
=> fix: search results not loading until search stopped

src/components/Modals/SearchModal/SearchModal.vue, src/lang/vi.js, src/services/qbit.js
I'm added Vietnamese Translation
=> Add Vietnamese

src/lang/id.js
When running the development build using `npm run serve` on the master branch, there are a ton of lint errors stemming from formatting issues with `src/lang/id.js`. This PR resolves that issue.
=> Fix lint errors in src/lang/id.js

src/components/Modals/SettingsModal/Tabs/Vuetorrent/General.vue, src/lang/ja.js
This PR adds support for the Japanese language.
=> perf: add Japanese language support

src/components/Core/SpeedCard.vue, src/components/Modals/SpeedLimitModal.vue, src/services/qbit.js
First of all, great project and a very clean code. Never used Vue before and I implemented this in less than an hour.
I tried to maximize the reuse in this pr that, as stated in the title, allows users to set global speed limits (both upload and download).
It reuses the SpeedLimitModal component that appears after clicking over the download and upload card speeds in the right drawer of the webpage.
Here is a screencast: https://watch.screencastify.com/v/a09SoF3H2Bt9flO7N1UI
(After settings the global limits you might observe some spikes in the reading of the speed data but the limits are correctly applied)
Closes #339
Enjoy 😃 
UPDATE: 
In a future update, we can also consider adding this stuff inside the settings
=> feat: add support for setting global speed limits

src/components/Modals/TorrentDetailModal/Tabs/Info.vue, src/lang/en.js
I (re-)added the original progress indicator with more fitting colors. 
Currently named and placed it based on the original row, but I'm open to suggestions.
| Light | Dark |
|---|---|
| ![image](https://user-images.githubusercontent.com/2472626/171060143-22bbd045-b467-48e3-95e3-faaac97b45c9.png) | ![image](https://user-images.githubusercontent.com/2472626/171060154-2e86af9d-c073-485b-a1c4-697dfac18e08.png) |
=> feat: piece states progress bar

public/index.html, src/App.vue
This PR improves accessibility for users that copy/paste text (like magnet links & password) with their mouse instead of keyboard shortcuts.
Original implementation: [a83ea144cf1daac09fc76feff5d03347c8ea87ca#diff-c2cc24bc9001b11b6add48a4cd8f893d5d6c6e4d1bd254158bd14ab997f552cdR12](https://github.com/WDaan/VueTorrent/commit/a83ea144cf1daac09fc76feff5d03347c8ea87ca#diff-c2cc24bc9001b11b6add48a4cd8f893d5d6c6e4d1bd254158bd14ab997f552cdR12)
=> fix: allow native context menu in input elements

src/components/Modals/AddModal.vue
- Simple change to category property so that the category download folder is shown as expected for the respective category.
- Fixes issue #440
- I don't use Automatic Torrent Managment but I done a test run with it and as long as you have provided a save path manually, it should populate too.
=> fix: Fix category download folder not showing correctly

src/components/TorrentDetail/Tabs/Content.vue, src/services/qbit.js
In v2.8.0 of the API, qbittorrent changed what parameters are required
for the `/torrents/renameFile` endpoint.  Instead of `hash`, `id`, and `name`,
the params are now `hash`, `oldPath`, and `newPath`.
[Current API spec for renameFile.](https://github.com/qbittorrent/qBittorrent/wiki/WebUI-API-(qBittorrent-4.1)#rename-file)
This fixes [issue 274](https://github.com/WDaan/VueTorrent/issues/274).
=> fix: renameFile returns 400 error

src/components/TorrentDetail/Tabs/Info.vue, src/filters.js, tests/unit/filters.spec.js
I have added filter to make _"Torrent Details"_ > _"Info"_ links clickable. Filter finds URL and replace it to <a> tag, so it becomes clickable. I have added this feature only to **tracker**, **created by** and **comment** fields, because only those fields can contain URL. This filter **will not** modify URLs which start without www/http/https (i.e. _something.com_) to prevent accidental replacement when sentence ends and new one starts without a space (i.e. _something cool.To replace_)
Also I'm participating in hacktoberfest, so it would help me alot if you can add "hacktoberfest-accepted" label to this PR :)
Related issue: https://github.com/WDaan/VueTorrent/issues/477
Pics:
=> feat: Links in torrent details view are now clickable

src/components/TorrentDetail/Tabs/Info.vue, src/components/TorrentDetail/Tabs/TorrentTagsAndCategories.vue, src/views/TorrentDetail.vue
I have fixed the issue, where after page refresh in TorrentDetail view, data was not rendered correctly - progress bar was empty. This was because template tried to render data before we can even access it from getTorrent store getter. I have passed torrent as a prop from parent. Actually this is proper way of doing it, so I'm planning to fix other tab items in my next PR, so we will avoid duplicate data fetching when opening these tabs and also will have consistent data on all tab items in TorrentDetail view. Let me know what you think about his :)
Also I have:
- set width for table, so it will not "jump" in width anymore.
- passed 'torrent' prop to TagsAndCategories, because there was an error when refreshing TorrentDetail view, that component couldn't access some properties from …
=> fix: Fixed torrent details info table rendering errors after page is refreshed

src/views/TorrentDetail.vue
**Super small but quality of life feature :)**
After navigating Single torrent > Right click > "Show info" torrent data gets stuck (not being updated anymore). This happens because Dashboard.vue and method which updates torrent data gets destroyed when other view is rendered. I have added dispatch _INIT_INTERVALS()_ method to TorrentDetails.vue _created()_ hook, to update torrent with latest data.
**Please add "hacktoberfest-accepted" to my PR :)**
=> fix: refresh torrent detail data from store 

src/App.vue
This is a very low effort fix for https://github.com/WDaan/VueTorrent/issues/414 & https://github.com/WDaan/VueTorrent/issues/498 though you might see the login prompt for a short moment before it disappears
=> fix: login prompt being displayed when whitelisted

README.md
I'm a first time contributor and wanted to investigate issue #488 because it seems like a reasonable and nice change to me.
So I cloned the repo and was greeted by a login screen. I didn't know where to lookup the username and password for authenticating in the WebUI. After a quick online search I found out it's the QB default. Since I needed to look this up as first time contributor I think this could help others too not get confused.
=> add mention of default username and password

src/components/Settings/Tabs/BitTorrent.vue, src/lang/en.js, tests/unit/BitTorrent.spec.js, tests/unit/__snapshots__/BitTorrent.spec.js.snap
Implements #483 
Wanted to open this as a draft since it's almost finished but also because I had to reverse engineer the thing a little bit here because [the following documentation](https://github.com/qbittorrent/qBittorrent/wiki/WebUI-API-(qBittorrent-4.1)#get-application-preferences) doesn't show correctly all the possible values assignable to the max_ratio_act param.
I've inspected it from the graphical qbittorrent instance running on my mac that the values are indeed four and go from 0 to 3 and the order is a bit fucked up. Look at this screen I've made that maps the index of the options within the select to the actual values:
=> feat: add max_ratio_act handling

src/views/Dashboard.vue
This PR debounces the Torrent search field in order to improve the responsiveness of the UI while typing.
It appears that searching is a pretty costly operation, which causes the entire tab to freeze when searching through lots of torrents, and debouncing it makes it smoother.
(Partially) addresses #540, additional work still needed to see if searching can be made faster/asynchronous at least.
=> perf: debounce torrent search field

src/components/Navbar/SpeedGraph.vue
This PR adds a `/s` suffix to the unit of the upload and download speed in the Graph navbar component.
=> fix: proper unit for up/dl speed in graph

src/components/TorrentDetail/Tabs/Info.vue
This PR adds a `/s` suffix to the unit of the upload and download speed in the Torrent Details view.
=> fix: proper unit for up/dl speed in details

src/services/qbit.ts
This PR fixes the `qbit.setTorrentName` using `GET` method instead of `POST`.
=> fix: Unable to rename torrent

src/components/Navbar/FilterSelect.vue, src/store/index.js
Loaded filters from store to display them in the navbar at startup
=> Fix: load missing filters at startup

src/components/Modals/AddModal.vue, src/components/Modals/TagsAndCategories/CreateTagDialog.vue, src/components/Navbar/FilterSelect.vue, src/components/Settings/Tabs/TagsAndCategories.vue, src/components/Torrent/DashboardItems/Tags.vue, src/components/Torrent/MobileCard.vue, src/components/Torrent/TorrentRightClickMenu.vue, src/components/TorrentDetail/Tabs/TorrentTagsAndCategories.vue, src/components/TorrentDetail/Tabs/index.js, src/lang/en.js, src/lang/fr.js, src/services/qbit.ts, src/store/actions.js, src/store/index.js, src/store/mutations.js, src/views/Dashboard.vue, src/views/TorrentDetail.vue
This PR adds the possibility to manage torrents' tags directly from the dashboard and while adding a new torrent and fixes the TorrentDetail vue to replace wrong component which prevented tags / category affectation.
Fixes #395
Fixes #473
Fixes #559
=> feat: Add tag support in Dashboard, TorrentDetail and Add Modal

src/components/Settings/Tabs/VueTorrent/Dashboard.vue, src/lang/en.js
Add new attribute to the settings menu
Note: By changing the store template in e242bad, users will have to delete their localStorage, for this change to take effect
=> Add "Completed On" to Dashboard customization settings

src/components/Modals/ChangeLocationModal.vue
Fixes change location not prefilling by using the first torrent savePath instead of using the settings' savePath.
Fixes #581
=> Fix default change location not prefilling

src/components/TorrentDetail/Tabs/Content.vue, src/lang/en.js, src/lang/es.js, src/lang/fr.js, src/lang/id.js, src/lang/it.js, src/lang/ja.js, src/lang/nl.js, src/lang/pt-br.js, src/lang/ru.js, src/lang/ua.js, src/lang/vi.js, src/lang/zh-hans.js, src/lang/zh-hant.js
Adds a toast to notify the user that the file / folder can't be renamed instead of silently ignoring it (VueTorrent still renames it in "local" though)
=> Add toast when renameFile and renameFolder failed

src/components/TorrentDetail/Tabs/Info.vue
Paints canvas when a file's piece is to be downloaded but not yet started.
=> Add pending pieces color to canvas

src/views/Dashboard.vue
Checks if the current page number is exceeding the total page count, and sets it to the last page if it's the case to prevent the dashboard from displaying an empty list of torrents.
Fixes #344
=> Reset pageNumber when changing filters to prevent value overflow

src/lang/zh-hant.js
I leave line 47 and 107 to be untouched since I can't find a good way to translate line 47 into Chinese and line 107 is related to line 47.
Detail:
In Chinese, the position of the numbers of "A of B" (e.g. 2 of 10) should be switched to become "B 中的 A" (e.g. 10 中的 2). It is beyond my ability so I leave it untouched for now.
=> chore: Update Traditional Chinese translation

src/components/TorrentDetail/Tabs/Content.vue, src/helpers.js
This PR fixes the 409 errors we received when trying to rename files and folders at least 1 level deep in the filetree.
Rework of the folder object construction in the local filetree and use of the fullPath attribute to include base path in the request.
=> Fix "409 Conflict" on file/folder rename

src/components/Settings/Tabs/VueTorrent/Dashboard.vue
This PR fixes dashboard items not using $store.state reference, hence not saving changes in the UI.
=> Fix dashboard items settings not saving

src/views/Dashboard.vue
Disabled hide condition on page scroll which prevented seeing the whole menu while using the WebUI on mobile with landscape orientation
=> perf: Disable hide condition on page scroll

src/components/TorrentDetail/Tabs/Content.vue
Optimised content tab's tree view for mobile devices.
Disable ellipsis on file and folder name.
Fixes #348
Fixes #585
=> Content tab improvements for mobile users

src/components/Modals/AddModal.vue, src/components/Modals/RenameModal.vue, src/views/Settings.vue, src/views/TorrentDetail.vue
Add keydown events on modals and views to close / submit
=> Add Enter / Escape keybinds to modals and views

src/store/index.js
Fix issue by duplicating properties template using JSON de-/serialization
Fixes #610
=> fix: Duplicate reference in dashboard settings

src/components/TorrentDetail/Tabs/Content.vue, src/components/TorrentDetail/Tabs/DetailPeers.vue, src/components/TorrentDetail/Tabs/Info.vue, src/components/TorrentDetail/Tabs/Trackers.vue
Forgot some deconstructors in the TS migration of the qbit service
=> fix: Invalid deconstruct on qbit service

src/components/Torrent/MobileCard.vue
=> fix: Forced state not present in MobileCard

src/views/RssArticles.vue
In light mode, the `white` rss unread item is completely invisible. After changing to `#ccc` color, you can clearly distinguish between read and unread
=> fix: change rss-unread color from white to #ccc

src/models/Status.ts
Stop all-time & session & disk-free data from zero-ing when 
`response.server_state` is sometimes null (for some reason)
=> fix zeroing

src/components/Modals/AddModal.vue, src/components/Torrent/TorrentRightClickMenu.vue, src/lang/en.json, src/lang/fr.json
Disable category selection in TRC menu if no categories are created just like tags were already done.
=> perf: Disable category selection in TRC menu if no categories are created

src/components/Modals/ConfirmShutdownModal.vue, src/components/Navbar/NavbarActions.vue, src/components/Navbar/TopActions.vue, src/lang/en.json, src/lang/fr.json
Added Shutdown confirmation Modal and moved previous shutdown button from TopActions to NavbarActions
Fixes #641
=> perf : Add shutdown confirmation modal + moved to NavbarActions

src/views/Dashboard.vue
Fixes: #253 
Fixed the annoying bug where the UI would select all visible torrents when you click CTRL + A while being focused on the filter/search input field
=> fix: Unwanted torrent selection during search

src/helpers.js
Handle '/' AND '\\' in torrents' content paths
Fixes #663
=> fix: Handle Windows path separators

src/services/qbit.ts
Replace `hashes` param with `hash` param to prevent 400
Fixes #667
=> fix: Fix 400 when adding trackers

src/enums/qbit/AppPreferences.ts
No idea why the two values got switched up
Source: https://github.com/qbittorrent/qBittorrent/blob/8df80b67f9f469a3240856f326d04da0ea221b11/src/base/bittorrent/session.h#L42-L50
Fixes #672
=> fix: Fix incorrect enum values for MaxRatioAction

src/views/Dashboard.vue, src/views/TorrentDetail.vue
This PR fixes a bug in the intervals used to refresh main data continuously.
Before this fix, when you opened a torrent detail then the settings view, after coming back to the main dashboard, the interval were duplicated, issuing 2 requests per 2 secs (the second one being almost always equal to 0 made the graph flickering between 0 and the actual value).
Previous behaviour:
- Dashboard: created -> mounted (INIT_INTERVALS)
- TorrentDetail: **created** (INIT_INTERVALS)
- overwriting dashboard's interval id
- Dashboard: beforeDestroy (REMOVE_INTERVALS)
- clearing TorrentDetail's interval and leaving dashboard's interval lost in the oblivion
- and thus causing the interval to duplicate each time the process is repeated
Fixed behaviour:
- Dashboard: created -> mounted (INIT_INTERVALS)
- …
=> fix: Fix intervals

src/views/Dashboard.vue
Added a shortcut to enable search filter if not already and focus the input.
=> perf: Add 'Ctrl + F' shortcut to focus search filter

src/components/TorrentDetail/Tabs/Trackers.vue, src/services/qbit.ts
- Fixes #697 : `hashes` -> `hash`
- Add missing `multiple` attribute on checkboxes that caused unexpected behaviour
=> fix: Fix trackers view

src/helpers.js
Missing brackets so condition was always evaluated to true cause function exists 😬
=> fix: Ctrl key not being handled on Windows/Linux

src/models/Torrent.ts
=> perf: improve format when using timestamp 0 on SeenComplete

package-lock.json, src/components/TorrentDetail/Tabs/Info.vue, src/filters.ts, src/lang/en.json, src/types/qbit/models/TorrentProperties.ts, src/views/TorrentDetail.vue
Adds missing attributes from the /torrent/properties route to the Torrent Info page
=> perf: Add missing torrent properties to TorrentDetail > Info

src/lang/zh-hans.json, src/store/getters.ts
Modified part of the problem that the display is correct in English but the word order is wrong in Chinese. Both Simplified Chinese and Traditional Chinese are supported, but this is a temporary fix. Because this problem may not exist after refactoring.
=> fix: fix the Chinese word order problem

src/components/Settings/Tabs/Downloads.vue
=> perf: Show autorun command tooltip when either checkbox is checked

src/components/Settings/Tabs/VueTorrent/VGeneral.vue, src/lang/en.json, tests/unit/__snapshots__/General.spec.ts.snap
Adds a button in the settings view to register magnet handler.
source: https://github.com/qbittorrent/qBittorrent/blob/cddf8c199cdc364548e2ca827ae37e92476515cd/src/webui/www/private/scripts/client.js#L1404-L1423
Fixes #111
Fixes #781
=> perf: Register magnet handler

package-lock.json, src/store/index.ts, src/store/mutations.ts, src/types/vuetorrent/StoreState.ts
This pull request limits `updateMainData` requests to at most one at the same time.
On my Raspberry Pi it can happen that a request takes longer than the interval (2 seconds in [current implementation](https://github.com/WDaan/VueTorrent/blob/2fdeb63c83eee6bbcdcc0bc639a4d3d303f10e20/src/store/actions.ts#L12)) when qBittorrent is busy. The current polling method, which makes a request every 2 seconds without exception, can cause multiple identical requests, resulting in even longer response time.
=> feat: limit updateMainData to one request at once

src/components/Settings/Tabs/Rss/Feeds.vue, src/components/Settings/Tabs/Rss/Rules.vue, src/lang/en.json
=> perf: Extend RSS Feeds / Rules to use full width instead of half

src/components/Settings/Tabs/WebUI.vue
Before:
- `settings.web_ui_password` doesn't exists
- enter text in text field
- remove text
- `settings.web_ui_password` is an empty string, so sent to `/setPreferences` endpoint and modifies password
After:
Each time `settings.web_ui_password` is empty, we replace it by `undefined` to prevent sending empty string
(I also added a toggle to hide / show password 👀)
=> fix: WebUI Password may be sent as empty string

src/components/Torrent/MobileCard.vue, src/enums/vuetorrent/DashboardProperty.ts, src/lang/en.json, src/lang/uk.json, src/store/actions.ts, src/store/getters.ts, src/store/index.ts, src/types/vuetorrent/StoreState.ts, src/views/Dashboard.vue
Add progress bar toggle in settings.
Add action in volatile store that triggers a toast when old settings are detected
Fix card errors which prevented torrents to render (kill issues)
Fixes #821
=> perf: Add progress bar toggle for mobile card

index.html
The body contains `oncontextmenu="return false"`, which, at least in all my test environments, causes all context menus to be blocked. This removes the ability to paste magnets on android (not sure about IOS).
The context-menu blocking is already handled by `blockContextMenu()` in `App.vue`, which handles TEXTAREAs etc. correctly, so this shouldn't break anything (according to my testing).
=> fix: context-menu not appearing

src/views/Dashboard.vue
If ctrl+F / cmd+F is pressed and search input is already focused, will trigger native find
Note: Nothing is told inside the app, I don't know if it's necessary and where it should be said.
=> perf: Allow native find

src/App.vue
Adds an exception to allow users to right click on <a> tags (links basically). This can be useful in the case where the user wants to open a link in a new tab / window / private window (e.g. rss article)
=> perf: Add right click exception on link elements

src/components/Navbar/Navbar.vue, src/lang/en.json, src/lang/zh-hant.json
Add text field query in the speed dial for active filters in the dashboard.
=> Add text filter in active filter tooltip

src/components/Navbar/Navbar.vue
Add null check to prevent speed dial from being stuck in errored state
=> fix: searchFilter is sometimes null

src/actions/Tags.ts, src/actions/Torrents.ts, src/components/Torrent/DashboardItems/Tags.vue, src/components/TorrentDetail/Tabs/Content.vue, src/components/TorrentDetail/Tabs/Info.vue, src/components/TorrentDetail/Tabs/Overview.vue, src/filters.ts, src/lang/en.json, src/models/Torrent.ts, src/views/TorrentDetail.vue
Adds a user-friendly tab to better visualize essential data in a dashboard-like style.
Desktop:
Mobile:
=> perf: Add TorrentDetail overview tab

src/components/Navbar/TopActions.vue
=> fix: transparent bg for speed dial

src/components/Navbar/TopActions.vue, src/components/Navbar/TopMenu.vue
#927 introduced a bug where the add torrent button were missing on desktop
=> chore: AddModal button not present on desktop

src/views/Logs.vue
Fix normal logs being white on a white background while using light theme.
Fixes #936
=> fix: light theme handling in logs view

src/components/TorrentDetail/Tabs/Overview.vue, src/lang/en.json, src/lang/zh-hant.json
=> perf(overview): Use selected file count instead of total file count

src/components/Navbar/TopMenu.vue
Following #935, button stopped working on mobile screen sizes.
=> fix(navbar): mobile plus button not working

src/components/Settings/Tabs/VueTorrent/VGeneral.vue, src/components/TorrentDetail/Tabs/Overview.vue, src/filters.ts, src/lang/en.json, src/schemas/StoreState.ts, src/store/index.ts, src/types/vuetorrent/WebUISettings.ts, tests/unit/__snapshots__/General.spec.ts.snap
- Improve layout
- Disable canvas reload with a lot of pieces
- Add store settings to configure large torrent threshold
=> perf(overview): Disable canvas generation on large torrents

package-lock.json, package.json
Revert SASS bump from dependabot (#885) to remove deprecation warnings.
Deprecation has been fixed with Vuetify 3. Update to Vue 3 will fix it as well.
=> chore: Revert sass bump

src/components/Torrent/TorrentRightClickMenu.vue
Only show "set priority" menu when torrent queuing is enabled
=> perf(TRC): Display "set priority" when queuing is enabled only

src/App.vue, src/components/Modals/ConfirmDeleteModal.vue, src/components/Navbar/TopActions.vue, src/views/Login.vue, src/views/MagnetHandler.vue
When on a TorrentDetail page, top actions will fire calls on currently focused torrent instead of selection / all.
*Added a redirect to dashboard when deleting torrent in that condition to prevent client errors.*
=> perf(torrentDetail): top actions fire on currently focused torrent

src/App.vue
When old session is expired, state is still authenticated so no redirect was made when the app was reloaded.
=> fix: App not redirecting to login page on load

src/components/TorrentDetail/Tabs/Overview.vue
Disable canvas first-time render to prevent freezes when opening Torrent Detail
Fixes #1023
=> perf(overview): Disable canvas first-time render

src/components/TorrentDetail/Tabs/Overview.vue
#1029 introduced a bug causing the canvas to render when it shouldn't and vice-versa
=> fix(overview): Canvas not displaying correctly

src/components/TorrentDetail/Tabs/DetailPeers.vue
In peer details screen we are seeing progress and relevance are shown with % associated to them.but the value returned over here is in terms of ratio. fixing this by multiplying value given by peer details call by 100.
closes https://github.com/WDaan/VueTorrent/issues/1033
after:
- [*] All Unit tests pass
=> fixing progress and relevance numbers in DetiledPeers screen

src/enums/vuetorrent/TorrentState.ts, src/models/Torrent.ts, src/plugins/vuetify.ts, src/styles/colors.scss, src/styles/styles.scss
A file is actively getting uploaded (seeding with upload speed) and a file which is being seeded but no uploading speed are both show with state as seeding and same colour.
To distinguish between these two files:
1. applying `Uploading` state to the torrent file
2. applying darker shade of blue to sideboarder to actively uploading files
PS: files force uploading will also be considered as uploading.
- [*] All Unit tests pass
=> adding darker colour to files actively or force uploading

src/models/Torrent.ts
Time Active row in Info tab has wrong format on longer duration than month. This is know issue with dayjs library.
=> fix(torrent): Wrong date format on longer duration than month

vite.config.js
In PWA mode, largest .js file was downloaded every time the app opens.
=> fix: app js file cached in PWA mode

vite.config.js
Font files with extensions woff and woff2 are now properly cached when app is istalled as PWA
=> fix: cache fonts in PWA mode

src/styles/styles.scss
On mobile, tab arrows with light theme remains nearly invisible dark color. PR fixes arrows to style them with light color.
=> fix(styles): overflowing tab arrows with light theme

src/router.ts, src/views/MagnetHandler.vue
when vuetorrent is used for magnet handling its not capturing whole magnet link rather it only captures till magnet:
Fixed this by using custom regex just for /download route.
Tested with single line and multiline magnet torrent links. Future testing is appreciated.
POT: 
https://github.com/WDaan/VueTorrent/assets/106881717/f48fde60-a7f2-423d-8a9c-0518880d5302
- [*] All Unit tests pass
=> fixing magnet handling

src/views/MagnetHandler.vue
In my Previous PR #1041 I have fixed magentHandling when unEncoded Magnet URL is used for magnetHandling. But this caused a issue with auto-grabing of Magnet links as these as Encoded from the Browser side. 
Fixing the issue introduced in above PR here.
Closes https://github.com/WDaan/VueTorrent/issues/1054
=> fixing magnet handling issue caused by #1041

src/helpers.js
This PR resolves an edge case where if a file extension contains the name of the parent folder, it fails to add that file to the content tree. Resolves #1052
- [x ] I've started from master
- [x ] I've only committed changes related to this PR
- [x ] All Unit tests pass
- [x ] I've removed all commented code
- [x ] I've removed all unneeded console.log statements
=> [fix]explicitly match the filename

src/filters.ts
in formatDataValues function we are using toPrecision funtion with precision value as 3 which when round off value reaches 4 digits returns exponential values. Fixed this by using checking if he value is above 999 and giving precision value 4 if the same is true.
Gave value :  
function returned :
=> fixing formatDataValues for values with 4 digits or more fixes #1079

src/views/Login.vue
Login by passing url query parameter `username` and `password` to route `login`
With this feature, if you open `http://some_address:8080/#/login?username=username&password=password` in the browser, you can login directly to the dashboard.
I propose this feature because I'm embedding VueTorrent to an iframe on my net disk 's web-ui, and I hope to save the trouble of typing username and password all over again.
If there's anything inappropriate with this proposal, please point it out and I will understand.
Finally, I really like this beautiful and powerful frontend. Lots of thanks to all your hard work.
=> feat!: Login with url query

src/components/Settings/VueTorrent/General.vue, src/composables/ArrayPagination.ts, src/locales/en.json, src/pages/Dashboard.vue, src/stores/vuetorrent.ts
Rework of #1151
After some experimentations, Vuetify's `v-infinite-scroll` component isn't suitable because we have a finite list of items.
I haven't tested on a significant amount of torrents (51 max), performance issues will probably occur on large collections.
=> feat(dashboard): Add infinite scroll

src/pages/Dashboard.vue
When holding a torrent then moving the view, right click action was still triggered.
=> fix(dashboard): Fix partial right click on mobile

src/pages/RssArticles.vue
When RSS articles had long names without any spaces, text wrap didn't occur with `v-list-item-title`'s style. Icons were shown outside screen in those cases.
=> fix(rss): Update overflow rules to handle long name without spaces

.github/workflows/release.yml
Not sure if it'll do the trick but the problem is that the checked out ref is the one before the release.
It can be an async problem between jobs (which the `needs` should fix) or a default value problem (fixed in this PR)
#1247
=> chore(ci): Fix version not up-to-date in release build

src/pages/Dashboard.vue
This should fix the problem, can't test because right click works perfectly fine everywhere except on iPhones.
Fixes #1290
=> fix(RightClickMenu): Fix target not being selected on long press

src/components/Dialogs/AddTorrentDialog.vue, src/services/qbit.ts, src/stores/torrents.ts, src/types/qbit/payloads/AddTorrentPayload.ts
Seems like `FormData::set` and `FormData::append` converts everything to string except files and blobs, including `null` and `undefined`.
Fixes #1326
=> fix(AddTorrentDialog): Prevent undefined values from being sent through API

src/components/Settings/RSS/General.vue, src/pages/RssArticles.vue, src/stores/vuetorrent.ts, src/types/qbit/models/FeedArticle.ts, src/types/vuetorrent/RssArticle.ts
Added a checkbox in the Settings/RSS page to use the `id` attribute instead of the `link` attribute.
Fixes #1270
=> feat(RSS): Add conf to use ID instead of link

src/components/Dashboard/DashboardItems/ItemDateTime.vue, src/components/Dashboard/DashboardItems/ItemDuration.vue, src/components/Dashboard/DashboardItems/ItemRelativeTime.vue, src/components/Dashboard/Views/Grid/GridView.vue, src/components/Dashboard/Views/Table/DashboardItems/ItemDateTime.vue, src/components/Dashboard/Views/Table/DashboardItems/ItemDuration.vue, src/components/Dashboard/Views/Table/TableView.vue, src/services/qbit.ts
- Added support for years and months
- Only include values starting at the first non-zero value
Fixes #1379
=> fix(duration): Values greater than a month weren't displayed

src/plugins/dayjs.ts
Fixes #1375
source: https://day.js.org/docs/en/customization/relative-time#relative-time-thresholds-and-rounding
=> perf: Prevent rounding for relative time values

src/helpers/data.spec.ts, src/helpers/number.spec.ts, src/helpers/number.ts
This PR reworks the toPrecision helper function previously returning :
- rounded floating-point values for percentages
- displays 100% progress on a downloading torrent which was misleading
- way too many decimals for binary values between 1000 and 1024
Before:
After:
=> fix(helpers): Rework toPrecision

src/App.vue, src/locales/en.json, src/pages/Logs.vue, src/stores/logs.ts
- Prevent log duplication
- Change unused sort to filter
Fixes #1282
Default sort order is still the same => in ascending order by log ID.
With the pagination in place, you can go to the last page with only one click. Moreover with the reversed sort order, each time logs are added it would shift the list by the added amount of logs which may be frustrating when looking at logs after some time.
=> feat(logs): Prevent duplication and add message filter

src/pages/Dashboard.vue
The V-Autocomplete component from Vuetify uses a hidden field to allow for user input. When not focused, this field is hidden using an `opacity: 0` rule, the component is still rendered which causes an overflow.
This PR overrides that rule to disable the render, thus not overflowing the field.
Fixes #1430
=> fix(sortBy): Fix height overflow

src/services/QbitProvider.ts
The absence of indexes in `getTorrentFiles`'s response made the request in `setTorrentFilePriority` impossible as it depends on them (id = index in the context).
The error only occurs with older version of Qbittorrent (< 4.4.0). PR that introduces indexes in the response: https://github.com/qbittorrent/qBittorrent/pull/14795
The fix manually add indexes on the returned array.
=> fix(QbitProvider): manually add indexes to getTorrentFiles response

src/components/TorrentDetail/Content/Content.vue, src/components/TorrentDetail/Overview.vue, src/locales/en.json, src/pages/TorrentDetail.vue
Filter file tree by `fullName` allowing to search through the entire file tree at once.
This was previously impossible with the virtual scroll not rendering all content nodes at once for performance reasons.
`fullName` is used instead of `name` to display a folder's subcontent in the resulting list.
=> perf(Content tab): Allow filtering files by name

src/composables/SearchQuery.spec.ts, src/composables/SearchQuery.ts
This PR adds unit tests for the SearchQuery composable and handles the dash sign to exclude tokens from results.
Close #1267 as other issues are already opened for each sub requests
=> perf(search): Handle dash (-) sign to exclude tokens from results

package-lock.json, package.json, src/components/Settings/VueTorrent/General.vue, src/components/TorrentDetail/Overview.vue, src/components/TorrentDetail/PieceCanvas.vue, src/locales/en.json, src/stores/vuetorrent.ts
* Implement WebGL/WebGPU rendering to better handle larger number of pieces (using pixi.js library)
* Re-work portion of rendering logic with very poor logarithmic efficiency (using @flatten-js/interval-tree library)
Working smoothly with 717590 pieces:
I probably need help reviewing that I've implemented this the right way, used the right conventions.  I've not worked with Vue or Typescript before so particularly type specifications and doing garbage collection on `onUnmounted` should be looked at to make sure I did those things correctly.
=> Optimize TorrentDetail Overview Piece Renderer

.vscode/extensions.json
Deleting Volar typescript plugin recommendation after deprecation
> This extension is deprecated. Use the "Vue - Official" (Vue.volar) extension instead.
=> chore: Update VSCode plugin recommendations

src/components/DnDZone.vue
When leaving the zone before the transition completes, the zone could get stuck in hover state, thus preventing any action on the UI unless another dnd action was initiated.
To fix this, I separated the background handling the drop/leave event, and the inner layout handling the transition.
=> perf(DnDZone): Prevent zone being stuck when leaving too early

public/registerSW.js
make sw.js work for url like 'https://mydomain.com/vuetorrent/', otherwise the console will output error.
=> fix(ServiceWorker): sw.js url

src/components/TorrentDetail/Content/Content.vue, src/stores/content.ts
Not sure about the PR title.
Basically I moved the filtering before the tree generation.
Actual behaviour:
`cachedFiles -> tree -> flatTree -> filteredTree`
This would cause a lot of issues:
- directory should be opened to filter its children
- This could add a lot of overhead and user actions on large torrents
- Filtering were applied on list entities
- This would hide the parent objects of a matching file
- Folder actions were not using the filter
- When marking a folder to download / changing priority, every child would be impacted regardless of the filter
- There were probably other stuff that were not convenient
New behaviour:
`cachedFiles -> filteredFiles -> tree -> flatTree`
By placing the filter before the tree generation allows for displaying the whole child structure of the …
=> perf(Content): Better handle tree filtering

src/components/Core/HistoryField.vue, src/components/Dialogs/BulkRenameFilesDialog.vue, src/constants/vuetorrent/HistoryKey.ts, src/locales/en.json, src/locales/zh-Hans.json, src/stores/content.ts, src/stores/vuetorrent.ts
https://github.com/VueTorrent/VueTorrent/assets/45785585/af75ef38-4606-4406-be48-e8c02ea66686
For #895.
The main functions are primarily referenced from https://github.com/qbittorrent/qBittorrent/pull/18287.
**Features**:
- Using regular expressions to handle renaming, supporting flags
- Expand/collapse folders, partial selection
- Identifying duplicate file names
- Identifying renaming result conflicts with original name
**Limitations**:
- Unable to rename folders
- Regular expressions only apply to file name and cannot be applied to the full path
=> feat(TorrentDetail): add bulk renaming

package-lock.json, package.json, src/components/Dialogs/BulkRenameFilesDialog.vue, src/components/Dialogs/PluginManagerDialog.vue, src/locales/en.json, src/pages/SearchEngine.vue, src/services/MockProvider.ts
* Mobile data tables are here!
* Clean BulkRenameFilesDialog, improve mobile layout and add missing key
* New mobile data table made the mobile layout completely unusable, had to rework it to simplify and make it usable again
* Other data tables were a lot simplier thus changes weren't needed
Old layout:
New layout:
=> chore(deps): Bump vuetify from 3.5.17 to 3.6.3

README.md, package-lock.json, package.json, src/components/Dialogs/PluginManagerDialog.vue, src/components/Settings/Downloads.vue, src/pages/SearchEngine.vue
Mobile data tables has been disabled by default in the latest version
=> chore(deps): Bump vuetify from 3.6.3 to 3.6.4

src/locales/en.json, src/pages/RssArticles.vue, src/stores/rss.ts
Fixes #1586. Simply adds a new `refreshAllFeeds()` to the rss store, complete with toast notification. Only thing missing are other translations, it only pulls from `en` right now.
First time using vue, it's very possible I messed up something obvious.
=> feat(RSS): add refresh all rss feeds button to rss articles

src/components/TorrentDetail/Peers.vue, src/services/qbit/MockProvider.ts, src/stores/torrents.ts
Bug was found on Discord by @krysalysm
Current behaviour:
- Only Tracker filter: 45 torrents
- Tracker and named tag: 33 torrents
- Tracker and untagged: **223** torrents (all untagged torrents)
Fixed behaviour:
- Only Tracker filter: 45 torrents
- Tracker and named tag: 33 torrents
- Tracker and untagged: **12** torrents
=> fix(filters): "Untagged" value don't using tracker filter when matched

src/components/Core/ColoredChip.vue, src/components/Dashboard/DashboardItems/ItemChip.vue, src/components/Dashboard/Views/Table/DashboardItems/ItemChip.vue, src/components/Settings/VueTorrent/General.vue, src/components/TorrentDetail/Overview.vue, src/locales/en.json, src/stores/vuetorrent.ts
- added an option to configure tags/categories without pill shape.
- can be achived thourgh enabling hide colered chips option in general settings.
https://youtu.be/42Y7L2RvH2g
=> feat(tags): option to have tags/categories without the “pill” shape (#1492)

src/components/Dashboard/Views/Table/DashboardItems/ItemAmount.vue, src/components/Dashboard/Views/Table/DashboardItems/ItemData.vue, src/components/Dashboard/Views/Table/DashboardItems/ItemDateTime.vue, src/components/Dashboard/Views/Table/DashboardItems/ItemDuration.vue, src/components/Dashboard/Views/Table/DashboardItems/ItemRelativeTime.vue, src/components/Dashboard/Views/Table/DashboardItems/ItemSpeed.vue, src/components/Dashboard/Views/Table/DashboardItems/ItemText.vue
in Table view the text items are wraping to 2 or more lines... more evident in low res screens.
This PR fixes that by adding <nobr> tag to all the elememts in table view.
alternatives tried using white-space : nowrap but it did not work. i heard its decrypted
result:
=> Fix: Do not wrap items to 2 or more lines in table view closes #1538

src/pages/Dashboard.vue, src/stores/dashboard.ts, src/stores/torrents.ts
Span selection was still using the unsorted list of filtered torrents, renamed exposed symbol to prevent future omissions.
=> fix(Dashboard): Fix span selection after #1740

src/components/Dialogs/AddTorrentDialog.vue, src/components/DnDZone.vue, src/locales/en.json, src/services/qbit/IProvider.ts, src/services/qbit/MockProvider.ts, src/services/qbit/QbitProvider.ts, src/stores/torrents.ts
Split DnDZone into 2 distinct fields:
- one for the same behavior "push to queue" at the top,
- and a new one to upload directly to qBittorrent (bottom)
[Desktop 2024.06.24 - 23.32.26.01.webm](https://github.com/VueTorrent/VueTorrent/assets/22910497/68db9ed9-b5fa-4ad6-80f9-e0f59d3f252f)
=> feat(Drag-and-Drop): Add instant download zone

.github/CONTRIBUTING.md, .github/ISSUE_TEMPLATE/config.yml, README.md
Add mail option to issue creation page for private requests and users without Discord accounts (either due to geo bans or for personal reasons)
=> chore: Add mail contact for private requests

.github/CONTRIBUTING.md, .github/ISSUE_TEMPLATE/config.yml
Mailto link doesn't work in issue templates. I suppose it's because of a non-HTTP(s) protocol.
=> chore: Move mailto link not working

src/stores/navbar.ts
Null values in series were causing weird / random breaks in the generated gradient.
Before:
After:
=> fix(graph): Fix weird gradient

src/components/TorrentDetail/Content/ContentNode.vue, src/types/vuetorrent/TreeObjects.ts
- Add selectedSize in node cache
- Change progress estimation from children progress average to children selectedSize percentage
- Given two files:
- size 5 Gb, 100% progress, selected
- size 5 kb, 0% progress, selected
- Before PR, 50% progress
- Now, 99.99%
=> perf(content): Improve progress accuracy

src/components/DnDZone.vue
**Deprecation Warning**: Sass's behavior for declarations that appear after nested rules will be changing to match the behavior specified by CSS in an upcoming version. To keep the existing behavior, move the declaration above the nested rule. To opt into the new behavior, wrap the declaration in `& {}`.
More info: https://sass-lang.com/d/mixed-decls
=> chore: Remove sass deprecation warnings

src/stores/content.ts
When using the "Recheck torrents on completion settings" and unchecking all files in a torrent, progress is considered 100% and a recheck event is fired.
To prevent this behaviour, we first select unwanted files before unselecting wanted files to always have at least one file checked in the process.
NB: Not sure if we should include it in the changelog, thus `chore`
=> chore(content): Swap order of invert priority calls to prevent file checking

src/App.vue, src/locales/en.json, src/stores/app.ts
Displays a pending toast when fetch time exceeds 1 sec, to prevent users from trying to login if they already are (bypass or old session still valid)
=> perf(App): Display loading toast when fetching login status

src/components/Dashboard/DashboardItems/ItemDuration.vue, src/components/Dashboard/Views/Table/DashboardItems/ItemDuration.vue, src/components/Settings/VueTorrent/General.vue, src/components/TorrentDetail/Info/PanelDuration.vue, src/constants/vuetorrent/index.ts, src/helpers/datetime.spec.ts, src/helpers/datetime.ts, src/helpers/index.ts, src/helpers/system.ts, src/locales/en.json, src/stores/vuetorrent.ts
Fixes #1818
Use configurable format for ItemDuration (in Dashboard).
PanelDuration uses the humanize method from dayjs, should we keep it or also move to the same format?
=> perf: Add configurable format for duration values

README.md, vite.config.ts
CSRF protection isn't interfering with the vite proxy, only Host header validation because of the port redirection.
=> chore(readme): Update dev env setup

src/components/Dashboard/Toolbar.vue, src/components/Navbar/Navbar.vue, src/components/TorrentSearchbar.vue, src/pages/Dashboard.vue
This PR implements a responsive search bar placement at the breakpoint of 1280px.
Above this breakpoint the search bar will be placed in the Navbar,
under this breakpoint the search bar will remain at it's current place.
With this change, each view type for the torrents will have more space, to display more torrents on desktop envs.
For this change the search bar got refactored into a Vue component called `TorrentSearchbar`.
Please check if the file for the component is in a folder to your liking.
Furthermore, some margins and paddings got changed to fix too small or too large gaps
and some elements got centered vertically to their parent component.
If any of the paddings or margins are not to your liking, please say so.
=> feat: responsive search bar placement

src/components/Navbar/TopWidgets/TopContainer.vue
Prevent active filter chip from overflowing (and being hidden) into the menu
Before:
After:
=> fix: Increase menu overflow threshold

src/components/Dashboard/Views/Table/TableView.vue
This PR implements a tooltip for the left torrent state indicator at the beginning of a line on the table view.
With this change the user is able to get information of a torrent's state without having the `State` column enabled,
saving valuable screen space and eventually preventing the torrent names from wrapping.
=> feat: tooltip on torrent state indicator for table view

src/components/Navbar/Navbar.vue
After merging #1883 the TorrentSearchbar now also has the dark mode color in light mode when placed in the Navbar.
This PR fixes the coloring issue for all themes (light/dark legacy/redesigned mode)
Old:
New/fixed:
=> fix: TorrentSearchbar color

src/App.vue, src/components/Dashboard/RightClick.vue, src/components/Dialogs/CategoryFormDialog.vue, src/components/Dialogs/ConfirmDeleteDialog.vue, src/components/Dialogs/TagFormDialog.vue, src/components/Settings/Advanced.vue, src/components/Settings/Connection.vue, src/components/Settings/Downloads.vue, src/components/Settings/RSS.vue, src/constants/qbit/AppPreferences.ts, src/locales/en.json, src/pages/SearchEngine.vue, src/services/qbit/IProvider.ts, src/services/qbit/MockProvider.ts, src/services/qbit/QbitProvider.ts, src/types/qbit/models/AppPreferences.ts
- SearchEngine:
- Replaced siteUrl with engineName and pubDate
- download torrent using plugin instead of adding to queue
- Settings:
- Advanced:
- torrent content remove option
- app instance name
- mark of the web
- python executable path
- I2P inbound/outbound quantity/length
- SSL torrents
- Connection:
- I2P support (address / port / mixed mode)
- Downloads:
- Unwanted folder
- category path in manual mode
- test email
- RSS:
- same domain fetch delay
=> feat(V5): Add new settings

src/pages/SearchEngine.vue, src/types/vuetorrent/SearchData.ts, src/types/vuetorrent/SearchResult.ts, src/types/vuetorrent/index.ts
#1952 
Changes download icon to a checkmark when a download has been issued for this result entry.
Also works for the old system pre-qbit 5 when adding to queue.
=> perf(SearchEngine): Improve download feedback

src/components/Dialogs/ConfirmDeleteDialog.vue, src/stores/preferences.ts, src/stores/vuetorrent.ts
Invalid map with the qBit 5 update, fixes #1951
Also used this for persisting the state on demand with the new flag, fixes #1907
On load (uses previous state so save action is disabled):
After change, button is unlocked:
On click, state has changed => disabled again:
=> perf(DeleteTorrentDialog): Remap incorrect binding and persist on-demand

src/components/TorrentDetail/Peers.vue
Fixes #1872
Occasionally the peer host gets the gateway IP which is a local IP address(as 192.168.0.1). Check whether to add blank before getting the flag.
=>   [fix] The peer info misplaced when no country flag returned.

src/components/Dashboard/Views/Grid/GridView.vue, src/components/Dashboard/Views/List/ListView.vue, src/components/Dashboard/Views/Table/TableView.vue, src/pages/Dashboard.vue
Reported on Discord, uses the same event handler for both the checkbox and the torrent card
=> fix(Dashboard): Make checkbox click events even with torrent card

src/constants/vuetorrent/Comparators.ts
Closes #1889.
This commit modifies the sorting logic for the `num_leechs` & `num_seeds` torrent sort keys.
The original sorting logic is maintained, however when torrents are "tied", the `available_peers` & `available_seeds` sort keys are used to further sort.
=> feat: Adding secondary sorts to peers and seeds

src/components/Dashboard/Views/Table/TableTorrent.vue, src/components/Dashboard/Views/Table/TableView.vue
#1401
Tried to have a width editable by the user, I haven't found a way yet.
Quick fix to restrict max width to 40% of the user screen.
=> fix(TableView): Set max width of torrent name to 40%

src/pages/Logs.vue, src/stores/logs.ts
Closes #2035
As requested, I have implemented a sort button in logs view
=> feat(Logs): Add sort support

src/stores/categories.ts, src/stores/content.ts, src/stores/tags.ts, src/stores/torrents.ts
Fixes #2048
#2049
Add exceptions in "Not working" filter.
List of excluded filters are all torrent states that don't communicate with external peers.
=> fix(filters): Don't count offline torrent in "Not working" tracker filter

src/components/Settings/Connection.vue
Previously, the I2P settings were disabled when I2P itself was disabled and vice versa, leading to the following:
This PR fixes this, so that you can edit the settings when I2P is enabled, and cannot when it is disabled.
=> Fixed disabling of i2p settings when i2p is enabled

src/components/DnDZone.vue
Handles torrent files and magnet / http(s) links.
Don't need secured context as it's an event initiated by the user.
Only works when an `<input>` tag isn't active.
=> perf: Handle paste event globally

src/App.vue, src/pages/TorrentDetail.vue, src/stores/global.ts, src/stores/index.ts
Fixes #2106
This PR adds 4 buttons to the Torrent Detail view. These buttons' actions are as follows from left to right:
- go to first filtered torrent
- go to previous filtered torrent
- go to next filtered torrent
- go to last filtered torrent
Also a new store has been introduced to allow for remounting the router component and ensure that lifecycle event are properly executed.
=> feat(TorrentDetail): Add torrent navigation buttons

src/components/Core/ColoredChip.vue, src/components/Settings/VueTorrent/General.vue, src/helpers/colors.ts, src/locales/en.json, src/themes/dark/oled.ts, src/themes/index.ts
https://github.com/VueTorrent/VueTorrent/issues/2092
I've imported functionality from `tinycolor` that darkens colors for OLED monitors. I've found that many of the dynamically generated colors for chips and other items are a bit too bright on OLED.
=> Feat: Add OLED theme

README.md
You have a broken markdown. `[!NOTE]` should be on a separate line in the README.md.
**Before:**
**After:**
=> fix: Readme markdown note (docs)

src/components/TorrentDetail/Overview.vue
`torrent.size` returns:
- Either the selected size if files are missing,
- Or downloaded size if all selected files are downloaded
=> fix(Overview): Use correct selected size

.github/workflows/test.yml, package-lock.json, package.json
Bump caused lint command to fail
=> chore(deps): Rollback @vue/eslint-config-typescript to 14.2.0

src/composables/BackendSync.ts
Fixes #2162
e2492aacbbcb2723828fcfb87b17d49afe6214c3 introduced a bug where a previous value would keep object references. It wouldn't trigger the update afterwards because `_lastState` object kept the reference to the new value, thus always returning true when comparing old and new state values.
=> fix(backend): Torrent properties not synced more than once

src/components/Settings/VueTorrent/General.vue, src/locales/en.json, src/stores/content.ts, src/stores/vuetorrent.ts
as discussed in #2159 and #2155, This PR introduces  a feature to toggle expand/collapse of content tab items by default.
this toggle can be set from General settings  `Expand content by default`
proof of testing:
https://github.com/user-attachments/assets/3e7966b2-628b-478d-b07f-0e804f9c7360
=> option to collapse/expand content items by default closes #2159

.github/workflows/build-release.yml
Can be safely deleted, job is alawys skipped and the backend successfully fetches the nightly without it.
=> chore(ci): Remove skipped pre-release job

src/components/Navbar/TopWidgets/ActiveFilters.vue
Fixes #1990
Disabled `open-on-click` on desktop and prevent menu from closing on any click in sub-chips => Reduce frustrating and precise mouse movements needed when disabling several filters at once.
Only main chip click has been kept for mobile to be able to open it, icon click is required in that case. Desktop behaviour is unaffected.
=> perf(ActiveFilters): Improve mouse events handling
